import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'lt' | 'en' | 'ru';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  lt: {
    // Header
    cart: 'Krepšelis',
    // Hero
    heroSubtitle: 'Aukščiausios kokybės Peptidai. Patikimi pardavėjai Lietuvoje jau daugiau nei pusmetį.',
    heroStat1: 'Šimtai patenkintų klientų',
    heroStat2: 'Greitas pristatymas visoje LT',
    heroStat3: '100% anonimiškas pirkimas',
    productsTitle: 'Produktai',
    loading: 'Kraunami produktai...',
    // About
    aboutTitle: 'Apie mus',
    aboutSubtitle: 'Patikimiausia Peptidų ir Steroidų parduotuvė Lietuvoje',
    aboutText1: 'Daugiau nei 6 mėnesius teikiame aukščiausios kokybės peptidus Lietuvos klientams.',
    aboutText2: 'Per šį laiką užsitarnavome šimtų klientų pasitikėjimą. Kiekvienas produktas tikrinamas ir siunčiamas rūpestingai, užtikrinant greitą ir saugų pristatymą.',
    aboutSlogan: 'Peptidai — ateities medicina.',
    stat1Title: '6+ mėnesiai rinkoje',
    stat1Desc: 'Patirtis ir klientų pasitikėjimas',
    stat2Title: 'Siuntimas 2-3 d.',
    stat2Desc: 'Visoje Lietuvoje į paštomatus',
    stat3Title: 'Anonimiškas pirkimas',
    stat3Desc: 'Jūsų privatumas — mūsų prioritetas',
    // Payment info
    paymentTitle: '100% Anonimiškas Mokėjimas Kriptovaliuta',
    paymentSubtitle: 'Be KYC, be tapatybės patvirtinimo',
    payBadge1: 'Be KYC',
    payBadge1Sub: 'Nereikia dokumentų',
    payBadge2: 'Anonimiškas',
    payBadge2Sub: '100% privatus',
    payBadge3: 'Greitas',
    payBadge3Sub: 'Kelios sekundės',
    payBadge4: 'Saugus',
    payBadge4Sub: 'Jūsų kontrolėje',
    choosePayment: 'Pasirinkite mokėjimo būdą — visi 100% anonimiški',
    onrampaBadge: 'IŠ KREPŠELIO',
    phantomBadge: 'REKOMENDUOJAMA',
    trustBadge: 'BE DOKUMENTŲ',
    revolutBadge: 'TIESIAI IŠ BANKO',
    exactSolWarning: 'SVARBU: išsiųskite tiksliai jūsų krepšeliui sugeneruotą SOL sumą. Išsiuntus netikslią sumą, užsakymas nebus patvirtintas.',
    howTo: 'Kaip?',
    // Onrampa guide
    onrampaFastest: 'MOKĖJIMAS IŠ KREPŠELIO',
    onrampaFastestDesc: 'Pirkite SOL tiesiogiai iš krepšelio su SEPA, kortele arba Apple Pay',
    onrampaStep1T: 'Pridėkite prekes į krepšelį',
    onrampaStep1D: 'Pasirinkite norimus produktus ir spauskite "Pereiti prie apmokėjimo". Sistema sugeneruos mokėjimo adresą ir tikslią sumą.',
    onrampaStep1Ok: 'Kaina apskaičiuojama automatiškai pagal dabartinį SOL kursą.',
    onrampaStep2T: 'Pasirinkite mokėjimo būdą',
    onrampaStep2D: 'Mokėkite SEPA banko pavedimu, kortele arba Apple Pay per Onramper platformą. Nereikia jokio crypto wallet.',
    onrampaStep3T: 'SOL atsiunčiamas automatiškai',
    onrampaStep3D: 'Nupirktas SOL automatiškai siunčiamas į jūsų užsakymo adresą. Sistema patvirtina mokėjimą per kelias minutes.',
    onrampaStep3Ok: 'Mokėjimas patvirtinamas automatiškai — jums nieko papildomai daryti nereikia.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — žingsniai',
    phantomDesc: 'Saugiausias ir populiariausias Solana wallet',
    phantomStep1T: 'Atsisiųskite Phantom',
    phantomStep1D: 'App Store arba Google Play — nemokama programėlė. Taip pat galima kaip Chrome naršyklės priedas.',
    phantomStep2T: 'Susikurkite piniginę',
    phantomStep2D: 'Spauskite "Create New Wallet". Išsaugokite 12 žodžių atkūrimo frazę saugioje vietoje.',
    phantomStep2W: 'Saugokite frazę — tai vienintelis būdas atkurti piniginę.',
    phantomStep3T: 'Nusipirkite SOL per Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). Mokėkite kortele arba Apple Pay. Pirkite ~5€ daugiau tinklo mokesčiams.',
    phantomStep3Ok: 'Greitas pirkimas tiesiai iš Phantom programėlės.',
    phantomStep4T: 'Išsiųskite SOL mums',
    phantomStep4D: 'Phantom → pasirinkite SOL → "Send" → įklijuokite mūsų adresą → įveskite tikslią sumą ir patvirtinkite.',
    phantomStep4Ok: 'Mokėjimas įvyksta per kelias sekundes. Po mokėjimo sistema automatiškai patvirtins.',
    // Trust guide
    trustTitle: 'Trust Wallet — žingsniai',
    trustDesc: 'Populiari mobili piniginė su paprasta SOL pirkimo galimybe',
    trustStep1T: 'Atsisiųskite Trust Wallet',
    trustStep1D: 'App Store (iPhone) arba Google Play (Android) — 100% nemokama ir saugi programėlė.',
    trustStep2T: 'Sukurkite naują piniginę',
    trustStep2D: 'Spauskite "Create New Wallet". Išsaugokite slaptą frazę (Recovery Phrase) saugioje vietoje.',
    trustStep2W: 'Saugokite slaptą frazę — tai vienintelis būdas atkurti piniginę.',
    trustStep3T: 'Nusipirkite SOL be KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". Mokėkite Apple Pay arba kortele. Pirkite ~5€ daugiau tinklo mokesčiams.',
    trustStep3Ok: 'Greitas pirkimas tiesiai iš Trust Wallet programėlės.',
    trustStep4T: 'Išsiųskite SOL mums',
    trustStep4D: 'Trust Wallet → pasirinkite SOL → "Send" → įklijuokite mūsų adresą → įveskite tikslią sumą ir patvirtinkite.',
    trustStep4Ok: 'Mokėjimas įvyksta per kelias sekundes. Sistema automatiškai patvirtins.',
    // Revolut guide
    revolutTitle: 'Revolut — žingsniai',
    revolutDesc: 'Turite Revolut? Galite pirkti SOL tiesiai per programėlę',
    revolutStep1T: 'Atidarykite Revolut programėlę',
    revolutStep1D: 'Eikite į skyrių "Crypto". Jei neturite Revolut — atsisiųskite iš App Store arba Google Play.',
    revolutStep2T: 'Nusipirkite SOL',
    revolutStep2D: 'Crypto → ieškokite "Solana (SOL)" → "Buy". Pirkite ~5€ daugiau tinklo mokesčiams. Atsiskaitymas iš Revolut balanso.',
    revolutStep3T: 'Persiųskite SOL į mūsų adresą',
    revolutStep3D: 'Crypto skyriuje pasirinkite SOL → "Send" → "External wallet" → įklijuokite mūsų Solana adresą → įveskite tikslią sumą.',
    revolutStep3W: 'Pastaba: Revolut gali taikyti išvedimo į išorinį wallet ribojimus priklausomai nuo jūsų paskyros lygio.',
    revolutStep4T: 'Mokėjimas patvirtinamas automatiškai',
    revolutStep4D: 'Sistema patikrins mokėjimą ir patvirtins užsakymą. Jei kyla klausimų — susisiekite Telegram.',
    revolutStep4Ok: 'Po mokėjimo parašykite: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Turite klausimų?',
    ctaAnswer: 'Atsakome greitai ir paprastai.',
    ctaTelegram: 'Rašykite Telegram: @Peptidai',
    ctaOperating: 'Veikiame jau daugiau nei 6 mėnesius',
    // Footer
    footerContact: 'Susisiekite su mumis',
    footerCopy: '© 2025–2026 Peptidai Lietuva. Visi produktai skirti tik mokslinių tyrimų tikslams.',
    footerDisclaimer: 'Visi produktai skirti tik in-vitro tyrimams ir edukaciniais tikslais. Nėra skirti žmonių vartojimui. Pirkdami patvirtinate, kad esate vyresnis nei 18 metų.',
    footerPrivacy: 'Privatumo politika',
    footerTerms: 'Naudojimo sąlygos',
    // Privacy Policy
    privacyTitle: 'Privatumo politika',
    privacyLastUpdated: 'Atnaujinta: 2025 m. sausio 1 d.',
    privacySection1Title: '1. Kokią informaciją renkame',
    privacySection1Text: 'Renkame tik užsakymui atlikti būtiną informaciją: telefono numerį ir paštomato pasirinkimą pristatymui. Nerenkame el. pašto adresų, vardų, pavardžių ar kitų asmeninių duomenų.',
    privacySection2Title: '2. Kaip naudojame informaciją',
    privacySection2Text: 'Jūsų pateiktą informaciją naudojame išimtinai užsakymų vykdymui ir pristatymui. Nesidalijame duomenimis su trečiosiomis šalimis, išskyrus pristatymo paslaugų teikėjus.',
    privacySection3Title: '3. Duomenų saugojimas',
    privacySection3Text: 'Duomenys saugomi šifruotose duomenų bazėse su ribota prieiga. Taikome pramonės standartų atitinkančias saugumo priemones duomenų apsaugai.',
    privacySection4Title: '4. Mokėjimų informacija',
    privacySection4Text: 'Mokėjimai vykdomi per blockchain tinklą. Mes nesaugome jokių finansinių duomenų ar mokėjimo kortelių informacijos. Visos transakcijos yra viešai matomos blockchain tinkle.',
    privacySection5Title: '5. Slapukai',
    privacySection5Text: 'Naudojame tik būtinus techninius slapukus svetainės veikimui užtikrinti. Nenaudojame analitinių ar reklaminių slapukų.',
    privacySection6Title: '6. Kontaktai',
    privacySection6Text: 'Dėl privatumo klausimų kreipkitės: peptidailietuva@gmail.com arba Telegram @Peptidai.',
    // Terms of Service
    termsTitle: 'Naudojimo sąlygos',
    termsLastUpdated: 'Atnaujinta: 2025 m. sausio 1 d.',
    termsSection1Title: '1. Paslaugų aprašymas',
    termsSection1Text: 'Peptidai Lietuva teikia tyrimo medžiagų ir peptidų pardavimo paslaugas. Visi produktai skirti išimtinai in-vitro tyrimams, edukaciniais ir moksliniais tikslais.',
    termsSection2Title: '2. Amžiaus apribojimas',
    termsSection2Text: 'Pirkėjas turi būti ne jaunesnis nei 18 metų. Pateikdami užsakymą patvirtinate, kad atitinkate šį reikalavimą.',
    termsSection3Title: '3. Produktų naudojimas',
    termsSection3Text: 'Visi produktai parduodami tik mokslinių tyrimų tikslams. Pirkėjas prisiima visą atsakomybę už produktų naudojimą pagal galiojančius įstatymus savo jurisdikcijoje.',
    termsSection4Title: '4. Mokėjimai ir grąžinimai',
    termsSection4Text: 'Mokėjimai priimami kriptovaliuta (SOL). Užsakymai patvirtinami automatiškai gavus mokėjimą. Grąžinimai galimi tik neišsiųstų užsakymų atveju, susisiekus su mumis per 24 valandas.',
    termsSection5Title: '5. Pristatymas',
    termsSection5Text: 'Pristatymas vykdomas per paštomatus Lietuvoje. Pristatymo laikas 1-3 darbo dienos. Nemokamas pristatymas užsakymams virš 50€.',
    termsSection6Title: '6. Atsakomybės ribojimas',
    termsSection6Text: 'Peptidai Lietuva neatsako už produktų naudojimą ne pagal paskirtį. Pirkėjas prisiima visą riziką ir atsakomybę.',
    termsSection7Title: '7. Kontaktai',
    termsSection7Text: 'Visais klausimais kreipkitės: peptidailietuva@gmail.com arba Telegram @Peptidai.',
    // Toast
    addedToCart: 'pridėtas į krepšelį!',
    // Cart
    cartTitle: 'Krepšelis',
    cartEmpty: 'Jūsų krepšelis tuščias',
    cartContinue: 'Tęsti apsipirkimą',
    cartProducts: 'Produktai:',
    cartShipping: 'Pristatymas:',
    cartFree: 'NEMOKAMAS',
    cartFreeMsg: 'Nemokamas pristatymas nuo 50€!',
    cartFreeUntil: 'Dar {amount}€ iki nemokamo pristatymo',
    cartTotal: 'Viso:',
    cartPaySol: 'Mokėsite SOL:',
    cartRate: 'Kursas:',
    cartLoadingRate: 'Kraunamas kursas...',
    cartUpdated: 'Atnaujinta:',
    cartCheckout: 'Pereiti prie apmokėjimo',
    cartSecure: 'Saugus pirkimas',
    cartAnon: 'Anonimiškas',
    cartDays: '2–3 d. d.',
    cartPrice: 'Kaina:',
    cartQty: 'vnt',
    // Checkout
    checkoutDelivery: 'Pristatymo informacija',
    checkoutPayment: 'Apmokėjimas',
    checkoutPhone: 'Telefono numeris',
    checkoutCity: 'Miestas',
    checkoutSelectCity: 'Pasirinkite miestą',
    checkoutSelectLocker: 'Pasirinkite paštomatą',
    checkoutLockerCode: 'Paštomato kodas:',
    checkoutDiscount: 'Nuolaidos kodas (neprivaloma)',
    checkoutDiscountApplied: '{code} — {percent}% nuolaida',
    checkoutRemove: 'Pašalinti',
    checkoutEnterCode: 'Įveskite kodą',
    checkoutApply: 'Taikyti',
    checkoutDiscountError: 'Nuolaidos kodas nerastas arba nebegalioja.',
    checkoutCodeError: 'Klaida tikrinant kodą. Bandykite dar kartą.',
    checkoutProducts: 'Produktai:',
    checkoutDiscountLine: 'Nuolaida ({code}, {percent}%):',
    checkoutShipping: 'Pristatymas:',
    checkoutTotal: 'Viso:',
    checkoutContinue: 'Tęsti prie apmokėjimo',
    checkoutCreating: 'Kuriamas užsakymas...',
    checkoutConfirm: 'Patvirtinti mokėjimą {amount} SOL',
    checkoutConfirmEur: 'Patvirtinti mokėjimą {amount}€',
    checkoutSelectMethod: 'Pasirinkite apmokėjimo būdą',
    checkoutBack: 'Atgal',
    checkoutFreeShipping: 'Nemokamas pristatymas nuo 50€!',
    checkoutFreeShippingAdd: 'Pridėkite dar {amount}€ ir gaukite nemokamą pristatymą!',
    // Onramp
    onrampEurLabel: 'Mokėjimo suma (su 5€ onramp fee):',
    onrampAutoNote: 'Sistema automatiškai aptiks mokėjimą ir patvirtins užsakymą. Nereikia siųsti tikslios SOL sumos.',
    onrampBuyTitle: 'Apmokėkite per Onramper',
    onrampStep1: 'Spauskite mygtuką žemiau — atsidarys Onramper puslapis',
    onrampStep2: 'Nusipirkite SOL už {amount}€ ir išsiųskite į mokėjimo adresą',
    onrampStep3: 'Įklijuokite mokėjimo adresą (nukopijuotas žemiau) ir apmokėkite',
    onrampBullet1: 'Nusipirkite SOL už {amount}€ per Onramper (SEPA/kortele/Apple Pay)',
    onrampBullet2: 'Sistema automatiškai patvirtins kai SOL atkeliaus į adresą',
    onrampGuideDesc: 'Nusipirkite SOL su banko pavedimu (SEPA), kortele arba Apple Pay ir išsiųskite į užsakymo adresą',
    onrampGuideStep1T: 'Patvirtinkite užsakymą',
    onrampGuideStep1B1: 'Patvirtinus užsakymą automatiškai atsidarys Onramper puslapis',
    onrampGuideStep1B2: 'Mokėjimo adresas bus nukopijuotas į jūsų clipboard',
    onrampGuideStep2T: 'Nusipirkite SOL',
    onrampGuideStep2B1: 'Nusipirkite SOL už {amount}€',
    onrampGuideStep2B2: 'Įklijuokite mokėjimo adresą (Ctrl+V) kaip gavėjo adresą',
    onrampGuideStep2B3: 'Pasirinkite mokėjimo būdą: SEPA, kortelė, Apple Pay',
    onrampGuideStep3T: 'Laukite patvirtinimo',
    onrampGuideStep3B1: 'SOL bus nusiųstas tiesiai į jūsų užsakymo adresą',
    onrampGuideStep3B2: 'Sistema automatiškai aptiks mokėjimą ir patvirtins užsakymą',
    pendingBuyOnramp: 'Pirkti SOL už {amount}€ — Onramper',
    pendingEurAmount: 'Mokėjimo suma:',
    // Pending
    pendingTitle: 'Laukiama apmokėjimo',
    pendingOrder: 'Užsakymas',
    pendingChecking: 'Tikrinamas mokėjimas...',
    pendingNext: 'Kitas patikrinimas po {time}s — sistema tikrina automatiškai',
    pendingSend: 'Siųsti mokėjimą',
    pendingExact: 'Tiksliai siųsti sumą:',
    pendingCopy: 'Kopijuoti',
    pendingCopied: 'Nukopijuota',
    pendingAddress: 'Siųsti į adresą:',
    pendingWarning: 'Siųskite TIKSLIAI nurodytą sumą SOL',
    pendingContact: 'Netikslios sumos atveju susisiekite:',
    pendingClose: 'Uždaryti',
    // Success
    successTitle: 'Užsakymas sukurtas!',
    successOrderNum: 'Užsakymo numeris',
    successConfirmed: 'Mokėjimas gautas ir patvirtintas!',
    successConfirmedMsg: 'Puiku! Gavome jūsų mokėjimą. Pristatysime užsakymą į pasirinktą paštomatą kuo greičiau.',
    successAwaitingPayment: 'Laukiama mokėjimo',
    successNextCheck: 'Kitas patikrinimas po {time}s',
    successMakePayment: 'Atlikite mokėjimą SOL (Solana)',
    successPaymentAmount: 'Mokėjimo suma:',
    successImportant: 'Svarbu:',
    successBullet3: 'Po mokėjimo susisiekite su mumis Telegram',
    successBullet1: 'Siųskite TIKSLIAI {amount} SOL',
    successBullet2: 'Naudokite Solana tinklą',
    successOrderInfo: 'Užsakymo informacija:',
    successPurchased: 'Pirkta:',
    successPhone: 'Telefonas:',
    successCity: 'Miestas:',
    successLocker: 'Paštomatas:',
    successSubtotal: 'Produktų suma:',
    successDiscountCode: 'Nuolaidos kodas:',
    successDiscount: 'Nuolaida ({percent}%):',
    successShipping: 'Pristatymas:',
    successTotalPaid: 'Viso mokėta:',
    successContact: 'Jei turite klausimų apie savo užsakymą, susisiekite:',
    successFinish: 'Baigti',
    // Checkout guides
    guideSolanaTitle: 'SOLANA APMOKEJIMO GIDAS',
    guideSolanaDesc: 'Tai saugiausias ir greičiausias būdas atsiskaityti',
    guidePhantom1T: 'Susikurkite Phantom wallet (2 min.)',
    guidePhantom1Desc: 'Rekomenduojame Phantom Wallet - paprasčiausia programėlė pradedantiesiems.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Atsisiųskite iš App Store arba Google Play arba Google Chrome Extension',
    guidePhantom1B1: 'Atsisiųskite iš App Store arba Google Play',
    guidePhantom1B2: 'Susikurkite naują wallet',
    guidePhantom1B3: 'SVARBU: Išsisaugokite 12 žodžių atkūrimo frazę (Seed Phrase)!',
    guidePhantom1B4: 'Nustatymuose Preferences pakeiskite valiutą iš $ į €',
    guidePhantom2T: 'Nusipirkite SOL tiesiai per Phantom',
    guidePhantom2B1: 'Spauskite "Buy" ir pasirinkite Solana (SOL)',
    guidePhantom2B2: 'Įveskite sumą: ~{amount}€ (pirkite ~5€ daugiau tinklo mokesčiams)',
    guidePhantom2B3: 'Provider sąraše spauskite "Fund Your Wallet"',
    guidePhantom2B4: 'Pasirinkite Solana (SOL)',
    guidePhantom2B5: 'Pasirinkite mokėjimo metodą',
    guidePhantom2B6: 'Atsiskaityti galima: kortele arba Apple Pay',
    guidePhantom2Note: 'Greitas pirkimas be KYC dokumento patikrinimo',
    guidePhantom3T: 'Išsiųskite SOL mums',
    guidePhantom3B1: 'Phantom wallet pasirinkite Solana',
    guidePhantom3B2: 'Spauskite "Send All"',
    guidePhantom3B3: 'Įklijuokite mūsų adresą',
    guidePhantom3B4: 'Siųsite sumą: {amount} SOL',
    guidePhantom3Note: 'Po siuntimo parašykite mums Telegram: @Peptidai',
    guideTrustTitle: 'PIRKIMAS BE DOKUMENTO (KYC)',
    guideTrustDesc: 'Naudokite Apple Pay arba kortelę — greitai ir paprastai',
    guideTrust1T: 'Atsisiųskite Trust Wallet',
    guideTrust1B1: 'Eikite į App Store arba Google Play',
    guideTrust1B2: 'Atsisiųskite "Trust Wallet" programėlę',
    guideTrust1B3: 'Susikurkite naują wallet ir išsisaugokite Seed Phrase',
    guideTrust2T: 'Nusipirkite SOL — spauskite "Fund Your Wallet"',
    guideTrust2B1: 'Spauskite "Buy" mygtuką programėlėje',
    guideTrust2B2: 'Pasirinkite Solana (SOL)',
    guideTrust2B3: 'Spauskite "Fund Your Wallet"',
    guideTrust2B4: 'Pasirinkite mokėjimo metodą: Apple Pay',
    guideTrust2B5: 'Pasirinkite mokėjimo metodą',
    guideTrust2B6: 'Įveskite sumą: ~{amount}€ ir apmokėkite',
    guideTrust2Note: 'Greitas pirkimas be KYC dokumento patikrinimo',
    guideTrust3T: 'Išsiųskite SOL mums',
    guideTrust3B1: 'Pasirinkite SOL savo paskyroje',
    guideTrust3B2: 'Spauskite "Send"',
    guideTrust3B3: 'Įklijuokite mūsų wallet adresą',
    guideTrust3B4: 'Įveskite sumą: {amount} SOL',
    guideTrust3B5: 'Patvirtinkite siuntimą',
    guideTrust3Note: 'Po mokėjimo parašykite: @Peptidai (Telegram)',
    guideRevolut1T: 'Atidarykite Revolut programėlę',
    guideRevolut1B1: 'Eikite į Revolut programėlę',
    guideRevolut1B2: 'Jei neturite - atsisiųskite iš App Store / Google Play',
    guideRevolut2T: 'Nusipirkite SOL per Revolut',
    guideRevolut2B1: 'Eikite į skyrių "Crypto"',
    guideRevolut2B2: 'Ieškokite Solana (SOL)',
    guideRevolut2B3: 'Spauskite "Buy"',
    guideRevolut2B4: 'Pirkite ~{amount}€ vertės SOL',
    guideRevolut3T: 'Persiųskite SOL į mūsų adresą',
    guideRevolut3B1: 'Crypto skyriuje pasirinkite SOL',
    guideRevolut3B2: 'Spauskite "Send" arba "Transfer"',
    guideRevolut3B3: 'Pasirinkite "External wallet"',
    guideRevolut3B4: 'Įveskite mūsų Solana adresą',
    guideRevolut3B5: 'Įveskite sumą: {amount} SOL',
    guideRevolutWarn: 'Pastaba: Revolut gali taikyti pervedimo į išorinį wallet ribojimus priklausomai nuo jūsų paskyros lygio.',
    guideRevolutNote: 'Po mokėjimo parašykite: @Peptidai (Telegram)',
    // ProductCard
    details: 'Detaliau',
    addToCart: 'Į krepšelį',
    comingSoon: 'Netrukus turėsime',
    // ProductDetail
    description: 'Aprašymas',
    selectQty: 'Pasirinkite kiekį',
    price: 'Kaina',
    delivery: 'Pristatymas',
    deliveryTime: 'Per 2-3 dienas',
    addToCartBtn: 'Pridėti į krepšelį',
    total: 'Viso:',
    freeShipping: 'NEMOKAMAS',
    paymentInfo: 'Mokėjimo informacija',
    exactSendAmount: 'Tiksliai siųsti sumą:',
    sendToAddress: 'Siųsti į adresą:',
    sendExact: 'Siųskite TIKSLIAI nurodytą sumą',
    orderAmount: 'Užsakymo suma',
    paymentMethodSol: 'Mokėjimas Solana (SOL)',
    exactAmountNote: 'Tikslus kiekis bus nurodytas apmokėjimo žingsnyje',
    errorTitle: 'Klaida:',
  },
  en: {
    // Header
    cart: 'Cart',
    // Hero
    heroSubtitle: 'Highest quality peptides. Trusted seller in Lithuania for over half a year.',
    heroStat1: 'Hundreds of satisfied customers',
    heroStat2: 'Fast delivery across Lithuania',
    heroStat3: '100% anonymous purchase',
    productsTitle: 'Products',
    loading: 'Loading products...',
    // About
    aboutTitle: 'About us',
    aboutSubtitle: 'The most trusted Peptides & Steroids store in Lithuania',
    aboutText1: 'For over 6 months we have been providing the highest quality peptides to Lithuanian customers.',
    aboutText2: 'In this time we have earned the trust of hundreds of customers. Each product is carefully checked and shipped, ensuring discreet and fast delivery.',
    aboutSlogan: 'Peptides — the medicine of the future.',
    stat1Title: '6+ months on the market',
    stat1Desc: 'Experience and customer trust',
    stat2Title: 'Shipping 2-3 days',
    stat2Desc: 'Across Lithuania to parcel lockers',
    stat3Title: 'Anonymous purchase',
    stat3Desc: 'Your privacy — our priority',
    // Payment info
    paymentTitle: '100% Anonymous Cryptocurrency Payment',
    paymentSubtitle: 'No KYC, no identity verification',
    payBadge1: 'No KYC',
    payBadge1Sub: 'No documents needed',
    payBadge2: 'Anonymous',
    payBadge2Sub: '100% private',
    payBadge3: 'Fast',
    payBadge3Sub: 'A few seconds',
    payBadge4: 'Secure',
    payBadge4Sub: 'In your control',
    choosePayment: 'Choose payment method — all 100% anonymous',
    onrampaBadge: 'FROM CART',
    phantomBadge: 'RECOMMENDED',
    trustBadge: 'NO DOCUMENTS',
    revolutBadge: 'DIRECT FROM BANK',
    exactSolWarning: 'IMPORTANT: send exactly the SOL amount generated for your cart. If the wrong amount is sent, the order will not be confirmed.',
    howTo: 'How?',
    // Onrampa guide
    onrampaFastest: 'PAY FROM CART',
    onrampaFastestDesc: 'Buy SOL directly from cart with SEPA, card or Apple Pay',
    onrampaStep1T: 'Add items to cart',
    onrampaStep1D: 'Select your products and click "Proceed to checkout". The system will generate a payment address and exact amount.',
    onrampaStep1Ok: 'Price is calculated automatically based on current SOL rate.',
    onrampaStep2T: 'Choose payment method',
    onrampaStep2D: 'Pay via SEPA bank transfer, card or Apple Pay through the Onramper platform. No crypto wallet needed.',
    onrampaStep3T: 'SOL sent automatically',
    onrampaStep3D: 'Purchased SOL is automatically sent to your order address. The system confirms payment within minutes.',
    onrampaStep3Ok: 'Payment confirmed automatically — no extra action needed.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — steps',
    phantomDesc: 'Safest and most popular Solana wallet',
    phantomStep1T: 'Download Phantom',
    phantomStep1D: 'App Store or Google Play — free app. Also available as Chrome extension.',
    phantomStep2T: 'Create a wallet',
    phantomStep2D: 'Click "Create New Wallet". Save the 12-word recovery phrase in a safe place.',
    phantomStep2W: 'Guard the phrase — it\'s the only way to restore the wallet.',
    phantomStep3T: 'Buy SOL through Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). Pay with card or Apple Pay. Buy ~€5 more for network fees.',
    phantomStep3Ok: 'Fast purchase directly from the Phantom app.',
    phantomStep4T: 'Send SOL to us',
    phantomStep4D: 'Phantom → select SOL → "Send" → paste our address → enter the exact amount and confirm.',
    phantomStep4Ok: 'Payment happens within seconds. System will auto-confirm after payment.',
    // Trust guide
    trustTitle: 'Trust Wallet — steps',
    trustDesc: 'Popular mobile wallet with easy SOL purchase',
    trustStep1T: 'Download Trust Wallet',
    trustStep1D: 'App Store (iPhone) or Google Play (Android) — 100% free and safe app.',
    trustStep2T: 'Create a new wallet',
    trustStep2D: 'Click "Create New Wallet". Save the secret phrase (Recovery Phrase) in a safe place.',
    trustStep2W: 'Guard the secret phrase — it\'s the only way to restore the wallet.',
    trustStep3T: 'Buy SOL without KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". Pay with Apple Pay or card. Buy ~€5 more for network fees.',
    trustStep3Ok: 'Fast purchase directly from the Trust Wallet app.',
    trustStep4T: 'Send SOL to us',
    trustStep4D: 'Trust Wallet → select SOL → "Send" → paste our address → enter the exact amount and confirm.',
    trustStep4Ok: 'Payment happens within seconds. System will auto-confirm.',
    // Revolut guide
    revolutTitle: 'Revolut — steps',
    revolutDesc: 'Have Revolut? You can buy SOL directly through the app',
    revolutStep1T: 'Open the Revolut app',
    revolutStep1D: 'Go to the "Crypto" section. If you don\'t have Revolut — download from App Store or Google Play.',
    revolutStep2T: 'Buy SOL',
    revolutStep2D: 'Crypto → search "Solana (SOL)" → "Buy". Buy ~€5 more for network fees. Payment from Revolut balance.',
    revolutStep3T: 'Transfer SOL to our address',
    revolutStep3D: 'In the Crypto section select SOL → "Send" → "External wallet" → paste our Solana address → enter exact amount.',
    revolutStep3W: 'Note: Revolut may apply withdrawal to external wallet restrictions depending on your account level.',
    revolutStep4T: 'Payment confirmed automatically',
    revolutStep4D: 'The system will check payment and confirm the order. If you have questions — contact Telegram.',
    revolutStep4Ok: 'After payment write: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Have questions?',
    ctaAnswer: 'We reply quickly, simply and discreetly.',
    ctaTelegram: 'Write Telegram: @Peptidai',
    ctaOperating: 'Operating for over 6 months',
    // Footer
    footerContact: 'Contact us',
    footerCopy: '© 2025–2026 Peptidai Lietuva. All products intended for scientific research purposes only.',
    footerDisclaimer: 'All products are intended for in-vitro research and educational purposes only. Not for human consumption. By purchasing you confirm that you are over 18 years of age.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    // Privacy Policy
    privacyTitle: 'Privacy Policy',
    privacyLastUpdated: 'Last updated: January 1, 2025',
    privacySection1Title: '1. Information We Collect',
    privacySection1Text: 'We collect only information necessary to fulfill your order: phone number and parcel locker selection for delivery. We do not collect email addresses, names, or other personal data.',
    privacySection2Title: '2. How We Use Information',
    privacySection2Text: 'Your information is used exclusively for order fulfillment and delivery. We do not share data with third parties, except delivery service providers.',
    privacySection3Title: '3. Data Storage',
    privacySection3Text: 'Data is stored in encrypted databases with restricted access. We apply industry-standard security measures for data protection.',
    privacySection4Title: '4. Payment Information',
    privacySection4Text: 'Payments are processed via blockchain network. We do not store any financial data or payment card information. All transactions are publicly visible on the blockchain.',
    privacySection5Title: '5. Cookies',
    privacySection5Text: 'We use only essential technical cookies required for website functionality. We do not use analytics or advertising cookies.',
    privacySection6Title: '6. Contact',
    privacySection6Text: 'For privacy-related inquiries: peptidailietuva@gmail.com or Telegram @Peptidai.',
    // Terms of Service
    termsTitle: 'Terms of Service',
    termsLastUpdated: 'Last updated: January 1, 2025',
    termsSection1Title: '1. Service Description',
    termsSection1Text: 'Peptidai Lietuva provides sales of research materials and peptides. All products are intended exclusively for in-vitro research, educational and scientific purposes.',
    termsSection2Title: '2. Age Restriction',
    termsSection2Text: 'Buyers must be at least 18 years of age. By placing an order you confirm that you meet this requirement.',
    termsSection3Title: '3. Product Use',
    termsSection3Text: 'All products are sold for scientific research purposes only. The buyer assumes full responsibility for product use in accordance with applicable laws in their jurisdiction.',
    termsSection4Title: '4. Payments and Refunds',
    termsSection4Text: 'Payments are accepted in cryptocurrency (SOL). Orders are confirmed automatically upon receiving payment. Refunds are possible only for unshipped orders, by contacting us within 24 hours.',
    termsSection5Title: '5. Delivery',
    termsSection5Text: 'Delivery is carried out via parcel lockers in Lithuania. Delivery time is 1-3 business days. Free shipping for orders over €50.',
    termsSection6Title: '6. Limitation of Liability',
    termsSection6Text: 'Peptidai Lietuva is not responsible for product use outside of intended purposes. The buyer assumes all risk and responsibility.',
    termsSection7Title: '7. Contact',
    termsSection7Text: 'For any questions contact: peptidailietuva@gmail.com or Telegram @Peptidai.',
    // Toast
    addedToCart: 'added to cart!',
    // Cart
    cartTitle: 'Cart',
    cartEmpty: 'Your cart is empty',
    cartContinue: 'Continue shopping',
    cartProducts: 'Products:',
    cartShipping: 'Shipping:',
    cartFree: 'FREE',
    cartFreeMsg: 'Free shipping from €50!',
    cartFreeUntil: 'Another {amount}€ until free shipping',
    cartTotal: 'Total:',
    cartPaySol: 'You will pay SOL:',
    cartRate: 'Rate:',
    cartLoadingRate: 'Loading rate...',
    cartUpdated: 'Updated:',
    cartCheckout: 'Proceed to checkout',
    cartSecure: 'Secure purchase',
    cartAnon: 'Anonymous',
    cartDays: '2–3 days',
    cartPrice: 'Price:',
    cartQty: 'pcs',
    // Checkout
    checkoutDelivery: 'Delivery information',
    checkoutPayment: 'Payment',
    checkoutPhone: 'Phone number',
    checkoutCity: 'City',
    checkoutSelectCity: 'Select city',
    checkoutSelectLocker: 'Select parcel locker',
    checkoutLockerCode: 'Locker code:',
    checkoutDiscount: 'Discount code (optional)',
    checkoutDiscountApplied: '{code} — {percent}% discount',
    checkoutRemove: 'Remove',
    checkoutEnterCode: 'Enter code',
    checkoutApply: 'Apply',
    checkoutDiscountError: 'Discount code not found or expired.',
    checkoutCodeError: 'Error checking code. Please try again.',
    checkoutProducts: 'Products:',
    checkoutDiscountLine: 'Discount ({code}, {percent}%):',
    checkoutShipping: 'Shipping:',
    checkoutTotal: 'Total:',
    checkoutContinue: 'Continue to payment',
    checkoutCreating: 'Creating order...',
    checkoutConfirm: 'Confirm payment {amount} SOL',
    checkoutConfirmEur: 'Confirm payment {amount}€',
    checkoutSelectMethod: 'Select payment method',
    checkoutBack: 'Back',
    checkoutFreeShipping: 'Free shipping from €50!',
    checkoutFreeShippingAdd: 'Add {amount}€ more for free shipping!',
    // Onramp
    onrampEurLabel: 'Payment amount (with €5 onramp fee):',
    onrampAutoNote: 'System will automatically detect the payment and confirm your order. No need to send an exact SOL amount.',
    onrampBuyTitle: 'Pay via Onramper',
    onrampStep1: 'Click the button below — Onramper page will open',
    onrampStep2: 'Buy SOL for {amount}€ and send to payment address',
    onrampStep3: 'Paste the payment address (copied below) and pay',
    onrampBullet1: 'Buy SOL for {amount}€ via Onramper (SEPA/card/Apple Pay)',
    onrampBullet2: 'System will automatically confirm when SOL arrives at the address',
    onrampGuideDesc: 'Buy SOL via bank transfer (SEPA), card or Apple Pay and send to your order address',
    onrampGuideStep1T: 'Confirm the order',
    onrampGuideStep1B1: 'After confirming, Onramper page will open automatically',
    onrampGuideStep1B2: 'Payment address will be copied to your clipboard',
    onrampGuideStep2T: 'Buy SOL',
    onrampGuideStep2B1: 'Buy SOL for {amount}€',
    onrampGuideStep2B2: 'Paste payment address (Ctrl+V) as recipient address',
    onrampGuideStep2B3: 'Select payment method: SEPA, card, Apple Pay',
    onrampGuideStep3T: 'Wait for confirmation',
    onrampGuideStep3B1: 'SOL will be sent directly to your order address',
    onrampGuideStep3B2: 'System will automatically detect payment and confirm your order',
    pendingBuyOnramp: 'Buy SOL for {amount}€ — Onramper',
    pendingEurAmount: 'Payment amount:',
    // Pending
    pendingTitle: 'Awaiting payment',
    pendingOrder: 'Order',
    pendingChecking: 'Checking payment...',
    pendingNext: 'Next check in {time}s — system checks automatically',
    pendingSend: 'Send payment',
    pendingExact: 'Send exact amount:',
    pendingCopy: 'Copy',
    pendingCopied: 'Copied',
    pendingAddress: 'Send to address:',
    pendingWarning: 'Send EXACTLY the specified SOL amount',
    pendingContact: 'If incorrect amount — contact:',
    pendingClose: 'Close',
    // Success
    successTitle: 'Order created!',
    successOrderNum: 'Order number',
    successConfirmed: 'Payment received and confirmed!',
    successConfirmedMsg: 'Great! We received your payment. We will deliver your order to the selected parcel locker as soon as possible.',
    successAwaitingPayment: 'Awaiting payment',
    successNextCheck: 'Next check in {time}s',
    successMakePayment: 'Make payment in SOL (Solana)',
    successPaymentAmount: 'Payment amount:',
    successImportant: 'Important:',
    successBullet3: 'Contact us via Telegram after payment',
    successBullet1: 'Send EXACTLY {amount} SOL',
    successBullet2: 'Use the Solana network',
    successOrderInfo: 'Order information:',
    successPurchased: 'Purchased:',
    successPhone: 'Phone:',
    successCity: 'City:',
    successLocker: 'Locker:',
    successSubtotal: 'Products total:',
    successDiscountCode: 'Discount code:',
    successDiscount: 'Discount ({percent}%):',
    successShipping: 'Shipping:',
    successTotalPaid: 'Total paid:',
    successContact: 'If you have questions about your order, contact:',
    successFinish: 'Finish',
    // Checkout guides
    guideSolanaTitle: 'SOLANA PAYMENT GUIDE',
    guideSolanaDesc: 'This is the safest and fastest way to pay',
    guidePhantom1T: 'Create Phantom wallet (2 min.)',
    guidePhantom1Desc: 'We recommend Phantom Wallet — the simplest app for beginners.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Download from App Store or Google Play or Google Chrome Extension',
    guidePhantom1B1: 'Download from App Store or Google Play',
    guidePhantom1B2: 'Create a new wallet',
    guidePhantom1B3: 'IMPORTANT: Save the 12-word recovery phrase (Seed Phrase)!',
    guidePhantom1B4: 'In Settings → Preferences change currency from $ to €',
    guidePhantom2T: 'Buy SOL directly through Phantom',
    guidePhantom2B1: 'Click "Buy" and select Solana (SOL)',
    guidePhantom2B2: 'Enter amount: ~{amount}€ (buy ~€5 more for network fees)',
    guidePhantom2B3: 'In the provider list click "Fund Your Wallet"',
    guidePhantom2B4: 'Select Solana (SOL)',
    guidePhantom2B5: 'Select payment method',
    guidePhantom2B6: 'Can pay with: card or Apple Pay',
    guidePhantom2Note: 'Fast purchase without KYC document verification',
    guidePhantom3T: 'Send SOL to us',
    guidePhantom3B1: 'In Phantom wallet select Solana',
    guidePhantom3B2: 'Click "Send All"',
    guidePhantom3B3: 'Paste our address',
    guidePhantom3B4: 'Amount to send: {amount} SOL',
    guidePhantom3Note: 'After sending write us on Telegram: @Peptidai',
    guideTrustTitle: 'PURCHASE WITHOUT DOCUMENT (KYC)',
    guideTrustDesc: 'Use Apple Pay or card — fast and simple',
    guideTrust1T: 'Download Trust Wallet',
    guideTrust1B1: 'Go to App Store or Google Play',
    guideTrust1B2: 'Download the "Trust Wallet" app',
    guideTrust1B3: 'Create a new wallet and save the Seed Phrase',
    guideTrust2T: 'Buy SOL — click "Fund Your Wallet"',
    guideTrust2B1: 'Click the "Buy" button in the app',
    guideTrust2B2: 'Select Solana (SOL)',
    guideTrust2B3: 'Click "Fund Your Wallet"',
    guideTrust2B4: 'Select payment method: Apple Pay',
    guideTrust2B5: 'Select payment method',
    guideTrust2B6: 'Enter amount: ~{amount}€ and pay',
    guideTrust2Note: 'Fast purchase without KYC document verification',
    guideTrust3T: 'Send SOL to us',
    guideTrust3B1: 'Select SOL in your account',
    guideTrust3B2: 'Click "Send"',
    guideTrust3B3: 'Paste our wallet address',
    guideTrust3B4: 'Enter amount: {amount} SOL',
    guideTrust3B5: 'Confirm the transfer',
    guideTrust3Note: 'After payment write: @Peptidai (Telegram)',
    guideRevolut1T: 'Open the Revolut app',
    guideRevolut1B1: 'Go to the Revolut app',
    guideRevolut1B2: 'If you don\'t have it — download from App Store / Google Play',
    guideRevolut2T: 'Buy SOL through Revolut',
    guideRevolut2B1: 'Go to the "Crypto" section',
    guideRevolut2B2: 'Search for Solana (SOL)',
    guideRevolut2B3: 'Click "Buy"',
    guideRevolut2B4: 'Buy ~{amount}€ worth of SOL',
    guideRevolut3T: 'Transfer SOL to our address',
    guideRevolut3B1: 'In the Crypto section select SOL',
    guideRevolut3B2: 'Click "Send" or "Transfer"',
    guideRevolut3B3: 'Select "External wallet"',
    guideRevolut3B4: 'Enter our Solana address',
    guideRevolut3B5: 'Enter amount: {amount} SOL',
    guideRevolutWarn: 'Note: Revolut may apply transfer to external wallet restrictions depending on your account level.',
    guideRevolutNote: 'After payment write: @Peptidai (Telegram)',
    // ProductCard
    details: 'Details',
    addToCart: 'Add to cart',
    comingSoon: 'Coming soon',
    // ProductDetail
    description: 'Description',
    selectQty: 'Select quantity',
    price: 'Price',
    delivery: 'Delivery',
    deliveryTime: 'Within 2-3 days',
    addToCartBtn: 'Add to cart',
    total: 'Total:',
    freeShipping: 'FREE',
    paymentInfo: 'Payment information',
    exactSendAmount: 'Send exact amount:',
    sendToAddress: 'Send to address:',
    sendExact: 'Send EXACTLY the specified amount',
    orderAmount: 'Order amount',
    paymentMethodSol: 'Payment via Solana (SOL)',
    exactAmountNote: 'Exact amount will be shown in the payment step',
    errorTitle: 'Error:',
  },
  ru: {
    // Header
    cart: 'Корзина',
    // Hero
    heroSubtitle: 'Пептиды высочайшего качества. Проверенный продавец в Литве уже более полугода.',
    heroStat1: 'Сотни довольных клиентов',
    heroStat2: 'Быстрая доставка по всей Литве',
    heroStat3: '100% анонимная покупка',
    productsTitle: 'Товары',
    loading: 'Загрузка товаров...',
    // About
    aboutTitle: 'О нас',
    aboutSubtitle: 'Самый надёжный магазин пептидов и стероидов в Литве',
    aboutText1: 'Более 6 месяцев мы предоставляем пептиды высочайшего качества клиентам Литвы.',
    aboutText2: 'За это время мы завоевали доверие сотен клиентов. Каждый товар тщательно проверяется и упаковывается, обеспечивая дискретную и быструю доставку.',
    aboutSlogan: 'Пептиды — медицина будущего.',
    stat1Title: '6+ месяцев на рынке',
    stat1Desc: 'Опыт и доверие клиентов',
    stat2Title: 'Доставка 2-3 дня',
    stat2Desc: 'По всей Литве в постоматы',
    stat3Title: 'Анонимная покупка',
    stat3Desc: 'Ваша конфиденциальность — наш приоритет',
    // Payment info
    paymentTitle: '100% Анонимная оплата криптовалютой',
    paymentSubtitle: 'Без KYC, без верификации личности',
    payBadge1: 'Без KYC',
    payBadge1Sub: 'Документы не нужны',
    payBadge2: 'Анонимно',
    payBadge2Sub: '100% приватно',
    payBadge3: 'Быстро',
    payBadge3Sub: 'Несколько секунд',
    payBadge4: 'Безопасно',
    payBadge4Sub: 'Под вашим контролем',
    choosePayment: 'Выберите способ оплаты — все 100% анонимны',
    onrampaBadge: 'ИЗ КОРЗИНЫ',
    phantomBadge: 'РЕКОМЕНДУЕМ',
    trustBadge: 'БЕЗ ДОКУМЕНТОВ',
    revolutBadge: 'ПРЯМО ИЗ БАНКА',
    exactSolWarning: 'ВАЖНО: отправьте точно ту сумму SOL, которая была сгенерирована для вашей корзины. При неточной сумме заказ не будет подтверждён.',
    howTo: 'Как?',
    // Onrampa guide
    onrampaFastest: 'ОПЛАТА ИЗ КОРЗИНЫ',
    onrampaFastestDesc: 'Купите SOL прямо из корзины через SEPA, карту или Apple Pay',
    onrampaStep1T: 'Добавьте товары в корзину',
    onrampaStep1D: 'Выберите нужные товары и нажмите "Перейти к оплате". Система сгенерирует адрес оплаты и точную сумму.',
    onrampaStep1Ok: 'Цена рассчитывается автоматически по текущему курсу SOL.',
    onrampaStep2T: 'Выберите способ оплаты',
    onrampaStep2D: 'Оплатите SEPA-переводом, картой или Apple Pay через платформу Onramper. Крипто-кошелёк не нужен.',
    onrampaStep3T: 'SOL отправляется автоматически',
    onrampaStep3D: 'Купленный SOL автоматически отправляется на адрес вашего заказа. Система подтверждает оплату в течение нескольких минут.',
    onrampaStep3Ok: 'Оплата подтверждается автоматически — никаких дополнительных действий не требуется.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — шаги',
    phantomDesc: 'Самый безопасный и популярный Solana кошелёк',
    phantomStep1T: 'Скачайте Phantom',
    phantomStep1D: 'App Store или Google Play — бесплатное приложение. Также доступно как расширение Chrome.',
    phantomStep2T: 'Создайте кошелёк',
    phantomStep2D: 'Нажмите "Create New Wallet". Сохраните 12-словную фразу восстановления в надёжном месте.',
    phantomStep2W: 'Сохраните фразу — это единственный способ восстановить кошелёк.',
    phantomStep3T: 'Купите SOL через Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). Оплата картой или Apple Pay. Купите ~€5 больше на комиссии сети.',
    phantomStep3Ok: 'Быстрая покупка прямо из приложения Phantom.',
    phantomStep4T: 'Отправьте SOL нам',
    phantomStep4D: 'Phantom → выберите SOL → "Send" → вставьте наш адрес → введите точную сумму и подтвердите.',
    phantomStep4Ok: 'Оплата занимает несколько секунд. Система автоматически подтвердит после оплаты.',
    // Trust guide
    trustTitle: 'Trust Wallet — шаги',
    trustDesc: 'Популярный мобильный кошелёк с простой покупкой SOL',
    trustStep1T: 'Скачайте Trust Wallet',
    trustStep1D: 'App Store (iPhone) или Google Play (Android) — 100% бесплатное и безопасное приложение.',
    trustStep2T: 'Создайте новый кошелёк',
    trustStep2D: 'Нажмите "Create New Wallet". Сохраните секретную фразу (Recovery Phrase) в надёжном месте.',
    trustStep2W: 'Сохраните секретную фразу — это единственный способ восстановить кошелёк.',
    trustStep3T: 'Купите SOL без KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". Оплата Apple Pay или картой. Купите ~€5 больше на комиссии сети.',
    trustStep3Ok: 'Быстрая покупка прямо из приложения Trust Wallet.',
    trustStep4T: 'Отправьте SOL нам',
    trustStep4D: 'Trust Wallet → выберите SOL → "Send" → вставьте наш адрес → введите точную сумму и подтвердите.',
    trustStep4Ok: 'Оплата занимает несколько секунд. Система автоматически подтвердит.',
    // Revolut guide
    revolutTitle: 'Revolut — шаги',
    revolutDesc: 'Есть Revolut? Можете купить SOL прямо через приложение',
    revolutStep1T: 'Откройте приложение Revolut',
    revolutStep1D: 'Перейдите в раздел "Crypto". Если нет Revolut — скачайте из App Store или Google Play.',
    revolutStep2T: 'Купите SOL',
    revolutStep2D: 'Crypto → ищите "Solana (SOL)" → "Buy". Купите ~€5 больше на комиссии сети. Оплата с баланса Revolut.',
    revolutStep3T: 'Переведите SOL на наш адрес',
    revolutStep3D: 'В разделе Crypto выберите SOL → "Send" → "External wallet" → вставьте наш Solana адрес → введите точную сумму.',
    revolutStep3W: 'Примечание: Revolut может применять ограничения на вывод во внешний кошелёк в зависимости от уровня вашего аккаунта.',
    revolutStep4T: 'Оплата подтверждается автоматически',
    revolutStep4D: 'Система проверит оплату и подтвердит заказ. Если есть вопросы — свяжитесь через Telegram.',
    revolutStep4Ok: 'После оплаты напишите: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Есть вопросы?',
    ctaAnswer: 'Отвечаем быстро, просто и дискретно.',
    ctaTelegram: 'Пишите в Telegram: @Peptidai',
    ctaOperating: 'Работаем уже более 6 месяцев',
    // Footer
    footerContact: 'Свяжитесь с нами',
    footerCopy: '© 2025–2026 Peptidai Lietuva. Все товары предназначены исключительно для научных исследований.',
    footerDisclaimer: 'Все продукты предназначены только для in-vitro исследований и образовательных целей. Не для употребления человеком. Совершая покупку, вы подтверждаете, что вам более 18 лет.',
    footerPrivacy: 'Политика конфиденциальности',
    footerTerms: 'Условия использования',
    // Privacy Policy
    privacyTitle: 'Политика конфиденциальности',
    privacyLastUpdated: 'Обновлено: 1 января 2025 г.',
    privacySection1Title: '1. Какую информацию мы собираем',
    privacySection1Text: 'Мы собираем только информацию, необходимую для выполнения заказа: номер телефона и выбор почтомата для доставки. Мы не собираем адреса электронной почты, имена или другие личные данные.',
    privacySection2Title: '2. Как мы используем информацию',
    privacySection2Text: 'Ваша информация используется исключительно для выполнения заказов и доставки. Мы не передаём данные третьим лицам, кроме служб доставки.',
    privacySection3Title: '3. Хранение данных',
    privacySection3Text: 'Данные хранятся в зашифрованных базах данных с ограниченным доступом. Мы применяем стандартные отраслевые меры безопасности для защиты данных.',
    privacySection4Title: '4. Платёжная информация',
    privacySection4Text: 'Платежи осуществляются через сеть blockchain. Мы не храним никаких финансовых данных или информации о платёжных картах. Все транзакции публично видны в блокчейне.',
    privacySection5Title: '5. Файлы cookie',
    privacySection5Text: 'Мы используем только необходимые технические файлы cookie для работы сайта. Мы не используем аналитические или рекламные файлы cookie.',
    privacySection6Title: '6. Контакты',
    privacySection6Text: 'По вопросам конфиденциальности: peptidailietuva@gmail.com или Telegram @Peptidai.',
    // Terms of Service
    termsTitle: 'Условия использования',
    termsLastUpdated: 'Обновлено: 1 января 2025 г.',
    termsSection1Title: '1. Описание услуг',
    termsSection1Text: 'Peptidai Lietuva предоставляет услуги по продаже исследовательских материалов и пептидов. Все продукты предназначены исключительно для in-vitro исследований, образовательных и научных целей.',
    termsSection2Title: '2. Возрастное ограничение',
    termsSection2Text: 'Покупатели должны быть не моложе 18 лет. Размещая заказ, вы подтверждаете соответствие этому требованию.',
    termsSection3Title: '3. Использование продуктов',
    termsSection3Text: 'Все продукты продаются только для научно-исследовательских целей. Покупатель берёт на себя полную ответственность за использование продуктов в соответствии с действующим законодательством.',
    termsSection4Title: '4. Оплата и возврат',
    termsSection4Text: 'Оплата принимается в криптовалюте (SOL). Заказы подтверждаются автоматически при получении оплаты. Возврат возможен только для неотправленных заказов, при обращении в течение 24 часов.',
    termsSection5Title: '5. Доставка',
    termsSection5Text: 'Доставка осуществляется через почтоматы в Литве. Срок доставки 1-3 рабочих дня. Бесплатная доставка для заказов свыше 50€.',
    termsSection6Title: '6. Ограничение ответственности',
    termsSection6Text: 'Peptidai Lietuva не несёт ответственности за использование продуктов не по назначению. Покупатель принимает на себя все риски и ответственность.',
    termsSection7Title: '7. Контакты',
    termsSection7Text: 'По любым вопросам обращайтесь: peptidailietuva@gmail.com или Telegram @Peptidai.',
    // Toast
    addedToCart: 'добавлен в корзину!',
    // Cart
    cartTitle: 'Корзина',
    cartEmpty: 'Ваша корзина пуста',
    cartContinue: 'Продолжить покупки',
    cartProducts: 'Товары:',
    cartShipping: 'Доставка:',
    cartFree: 'БЕСПЛАТНО',
    cartFreeMsg: 'Бесплатная доставка от 50€!',
    cartFreeUntil: 'Ещё {amount}€ до бесплатной доставки',
    cartTotal: 'Итого:',
    cartPaySol: 'Вы заплатите SOL:',
    cartRate: 'Курс:',
    cartLoadingRate: 'Загрузка курса...',
    cartUpdated: 'Обновлено:',
    cartCheckout: 'Перейти к оплате',
    cartSecure: 'Безопасная покупка',
    cartAnon: 'Анонимно',
    cartDays: '2–3 дня',
    cartPrice: 'Цена:',
    cartQty: 'шт',
    // Checkout
    checkoutDelivery: 'Информация о доставке',
    checkoutPayment: 'Оплата',
    checkoutPhone: 'Номер телефона',
    checkoutCity: 'Город',
    checkoutSelectCity: 'Выберите город',
    checkoutSelectLocker: 'Выберите постомат',
    checkoutLockerCode: 'Код постомата:',
    checkoutDiscount: 'Код скидки (необязательно)',
    checkoutDiscountApplied: '{code} — скидка {percent}%',
    checkoutRemove: 'Удалить',
    checkoutEnterCode: 'Введите код',
    checkoutApply: 'Применить',
    checkoutDiscountError: 'Код скидки не найден или недействителен.',
    checkoutCodeError: 'Ошибка проверки кода. Попробуйте ещё раз.',
    checkoutProducts: 'Товары:',
    checkoutDiscountLine: 'Скидка ({code}, {percent}%):',
    checkoutShipping: 'Доставка:',
    checkoutTotal: 'Итого:',
    checkoutContinue: 'Перейти к оплате',
    checkoutCreating: 'Создание заказа...',
    checkoutConfirm: 'Подтвердить оплату {amount} SOL',
    checkoutConfirmEur: 'Подтвердить оплату {amount}€',
    checkoutSelectMethod: 'Выберите способ оплаты',
    checkoutBack: 'Назад',
    checkoutFreeShipping: 'Бесплатная доставка от 50€!',
    checkoutFreeShippingAdd: 'Добавьте ещё {amount}€ для бесплатной доставки!',
    // Onramp
    onrampEurLabel: 'Сумма оплаты (с комиссией 5€ onramp):',
    onrampAutoNote: 'Система автоматически обнаружит платёж и подтвердит заказ. Не нужно отправлять точную сумму SOL.',
    onrampBuyTitle: 'Оплатите через Onramper',
    onrampStep1: 'Нажмите кнопку ниже — откроется страница Onramper',
    onrampStep2: 'Купите SOL на {amount}€ и отправьте на адрес оплаты',
    onrampStep3: 'Вставьте адрес оплаты (скопирован ниже) и оплатите',
    onrampBullet1: 'Купите SOL на {amount}€ через Onramper (SEPA/карта/Apple Pay)',
    onrampBullet2: 'Система автоматически подтвердит когда SOL поступит на адрес',
    onrampGuideDesc: 'Купите SOL банковским переводом (SEPA), картой или Apple Pay и отправьте на адрес заказа',
    onrampGuideStep1T: 'Подтвердите заказ',
    onrampGuideStep1B1: 'После подтверждения автоматически откроется страница Onramper',
    onrampGuideStep1B2: 'Адрес оплаты будет скопирован в буфер обмена',
    onrampGuideStep2T: 'Купите SOL',
    onrampGuideStep2B1: 'Купите SOL на {amount}€',
    onrampGuideStep2B2: 'Вставьте адрес оплаты (Ctrl+V) как адрес получателя',
    onrampGuideStep2B3: 'Выберите способ оплаты: SEPA, карта, Apple Pay',
    onrampGuideStep3T: 'Дождитесь подтверждения',
    onrampGuideStep3B1: 'SOL будет отправлен прямо на адрес вашего заказа',
    onrampGuideStep3B2: 'Система автоматически обнаружит платёж и подтвердит заказ',
    pendingBuyOnramp: 'Купить SOL на {amount}€ — Onramper',
    pendingEurAmount: 'Сумма оплаты:',
    // Pending
    pendingTitle: 'Ожидание оплаты',
    pendingOrder: 'Заказ',
    pendingChecking: 'Проверка оплаты...',
    pendingNext: 'Следующая проверка через {time}с — система проверяет автоматически',
    pendingSend: 'Отправить оплату',
    pendingExact: 'Отправить точную сумму:',
    pendingCopy: 'Копировать',
    pendingCopied: 'Скопировано',
    pendingAddress: 'Отправить на адрес:',
    pendingWarning: 'Отправьте ТОЧНО указанную сумму SOL',
    pendingContact: 'При неточной сумме свяжитесь:',
    pendingClose: 'Закрыть',
    // Success
    successTitle: 'Заказ создан!',
    successOrderNum: 'Номер заказа',
    successConfirmed: 'Оплата получена и подтверждена!',
    successConfirmedMsg: 'Отлично! Мы получили ваш платёж. Доставим заказ в выбранный постамат как можно скорее.',
    successAwaitingPayment: 'Ожидание оплаты',
    successNextCheck: 'Следующая проверка через {time}с',
    successMakePayment: 'Произведите оплату SOL (Solana)',
    successPaymentAmount: 'Сумма оплаты:',
    successImportant: 'Важно:',
    successBullet3: 'После оплаты свяжитесь с нами через Telegram',
    successBullet1: 'Отправьте ТОЧНО {amount} SOL',
    successBullet2: 'Используйте сеть Solana',
    successOrderInfo: 'Информация о заказе:',
    successPurchased: 'Куплено:',
    successPhone: 'Телефон:',
    successCity: 'Город:',
    successLocker: 'Постомат:',
    successSubtotal: 'Сумма товаров:',
    successDiscountCode: 'Код скидки:',
    successDiscount: 'Скидка ({percent}%):',
    successShipping: 'Доставка:',
    successTotalPaid: 'Итого оплачено:',
    successContact: 'Если у вас есть вопросы по заказу, свяжитесь:',
    successFinish: 'Завершить',
    // Checkout guides
    guideSolanaTitle: 'РУКОВОДСТВО ПО ОПЛАТЕ SOLANA',
    guideSolanaDesc: 'Это самый безопасный и быстрый способ оплаты',
    guidePhantom1T: 'Создайте Phantom кошелёк (2 мин.)',
    guidePhantom1Desc: 'Рекомендуем Phantom Wallet — самое простое приложение для начинающих.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Скачайте из App Store, Google Play или как расширение Chrome',
    guidePhantom1B1: 'Скачайте из App Store или Google Play',
    guidePhantom1B2: 'Создайте новый кошелёк',
    guidePhantom1B3: 'ВАЖНО: Сохраните 12-словную фразу восстановления (Seed Phrase)!',
    guidePhantom1B4: 'В Настройках → Preferences измените валюту с $ на €',
    guidePhantom2T: 'Купите SOL прямо через Phantom',
    guidePhantom2B1: 'Нажмите "Buy" и выберите Solana (SOL)',
    guidePhantom2B2: 'Введите сумму: ~{amount}€ (купите ~€5 больше на комиссии сети)',
    guidePhantom2B3: 'В списке провайдеров нажмите "Fund Your Wallet"',
    guidePhantom2B4: 'Выберите Solana (SOL)',
    guidePhantom2B5: 'Выберите способ оплаты',
    guidePhantom2B6: 'Можно оплатить: картой или Apple Pay',
    guidePhantom2Note: 'Быстрая покупка без KYC верификации документов',
    guidePhantom3T: 'Отправьте SOL нам',
    guidePhantom3B1: 'В кошельке Phantom выберите Solana',
    guidePhantom3B2: 'Нажмите "Send All"',
    guidePhantom3B3: 'Вставьте наш адрес',
    guidePhantom3B4: 'Сумма к отправке: {amount} SOL',
    guidePhantom3Note: 'После отправки напишите нам в Telegram: @Peptidai',
    guideTrustTitle: 'ПОКУПКА БЕЗ ДОКУМЕНТОВ (KYC)',
    guideTrustDesc: 'Используйте Apple Pay или карту — быстро и просто',
    guideTrust1T: 'Скачайте Trust Wallet',
    guideTrust1B1: 'Перейдите в App Store или Google Play',
    guideTrust1B2: 'Скачайте приложение "Trust Wallet"',
    guideTrust1B3: 'Создайте новый кошелёк и сохраните Seed Phrase',
    guideTrust2T: 'Купите SOL — нажмите "Fund Your Wallet"',
    guideTrust2B1: 'Нажмите кнопку "Buy" в приложении',
    guideTrust2B2: 'Выберите Solana (SOL)',
    guideTrust2B3: 'Нажмите "Fund Your Wallet"',
    guideTrust2B4: 'Выберите способ оплаты: Apple Pay',
    guideTrust2B5: 'Выберите способ оплаты',
    guideTrust2B6: 'Введите сумму: ~{amount}€ и оплатите',
    guideTrust2Note: 'Быстрая покупка без KYC верификации документов',
    guideTrust3T: 'Отправьте SOL нам',
    guideTrust3B1: 'Выберите SOL в своём аккаунте',
    guideTrust3B2: 'Нажмите "Send"',
    guideTrust3B3: 'Вставьте адрес нашего кошелька',
    guideTrust3B4: 'Введите сумму: {amount} SOL',
    guideTrust3B5: 'Подтвердите отправку',
    guideTrust3Note: 'После оплаты напишите: @Peptidai (Telegram)',
    guideRevolut1T: 'Откройте приложение Revolut',
    guideRevolut1B1: 'Перейдите в приложение Revolut',
    guideRevolut1B2: 'Если нет — скачайте из App Store / Google Play',
    guideRevolut2T: 'Купите SOL через Revolut',
    guideRevolut2B1: 'Перейдите в раздел "Crypto"',
    guideRevolut2B2: 'Ищите Solana (SOL)',
    guideRevolut2B3: 'Нажмите "Buy"',
    guideRevolut2B4: 'Купите SOL на ~{amount}€',
    guideRevolut3T: 'Переведите SOL на наш адрес',
    guideRevolut3B1: 'В разделе Crypto выберите SOL',
    guideRevolut3B2: 'Нажмите "Send" или "Transfer"',
    guideRevolut3B3: 'Выберите "External wallet"',
    guideRevolut3B4: 'Введите наш Solana адрес',
    guideRevolut3B5: 'Введите сумму: {amount} SOL',
    guideRevolutWarn: 'Примечание: Revolut может применять ограничения на вывод во внешний кошелёк в зависимости от уровня вашего аккаунта.',
    guideRevolutNote: 'После оплаты напишите: @Peptidai (Telegram)',
    // ProductCard
    details: 'Подробнее',
    addToCart: 'В корзину',
    comingSoon: 'Скоро в наличии',
    // ProductDetail
    description: 'Описание',
    selectQty: 'Выберите количество',
    price: 'Цена',
    delivery: 'Доставка',
    deliveryTime: 'За 2-3 дня',
    addToCartBtn: 'Добавить в корзину',
    total: 'Итого:',
    freeShipping: 'БЕСПЛАТНО',
    paymentInfo: 'Информация об оплате',
    exactSendAmount: 'Отправить точную сумму:',
    sendToAddress: 'Отправить на адрес:',
    sendExact: 'Отправьте ТОЧНО указанную сумму',
    orderAmount: 'Сумма заказа',
    paymentMethodSol: 'Оплата через Solana (SOL)',
    exactAmountNote: 'Точная сумма будет указана на шаге оплаты',
    errorTitle: 'Ошибка:',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('lt');

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['lt'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
