import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'lt' | 'en' | 'ru';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  lt: {
    // Header
    cart: 'Krepšelis',
    // Hero
    heroSubtitle: 'Aukščiausios kokybės Peptidai. Pirmieji tiekėjai Lietuvoje nuo 2025m.',
    heroStat1: 'Šimtai patenkintų klientų',
    heroStat2: 'Greitas pristatymas visoje LT',
    heroStat3: '100% anonimiškas pirkimas',
    productsTitle: 'Produktai',
    loading: 'Kraunami produktai...',
    // About
    aboutTitle: 'Apie mus',
    aboutSubtitle: 'Patikimiausia Peptidų ir Steroidų parduotuvė Lietuvoje',
    aboutText1: 'Nuo 2025 metų teikiame aukščiausios kokybės peptidus Lietuvos klientams.',
    aboutText2: 'Per šį laiką užsitarnavome šimtų klientų pasitikėjimą. Kiekvienas produktas tikrinamas ir siunčiamas rūpestingai, užtikrinant greitą ir saugų pristatymą.',
    aboutSlogan: 'Peptidai — ateities medicina.',
    stat1Title: 'Dirbame nuo 2025m.',
    stat1Desc: 'Patirtis ir klientų pasitikėjimas',
    stat2Title: 'Siuntimas 2-3 d.',
    stat2Desc: 'Visoje Lietuvoje į paštomatus',
    stat3Title: 'Anonimiškas pirkimas',
    stat3Desc: 'Jūsų privatumas — mūsų prioritetas',
    // Payment info
    paymentTitle: '100% Anonimiškas Mokėjimas Kriptovaliuta',
    paymentSubtitle: 'Be KYC, be tapatybės patvirtinimo',
    payBadge1: 'Be KYC',
    payBadge1Sub: 'Nereikia dokumentų',
    payBadge2: 'Anonimiškas',
    payBadge2Sub: '100% privatus',
    payBadge3: 'Greitas',
    payBadge3Sub: 'Kelios sekundės',
    payBadge4: 'Saugus',
    payBadge4Sub: 'Jūsų kontrolėje',
    choosePayment: 'Pasirinkite mokėjimo būdą — visi 100% anonimiški',
    swapsBadge: 'GREIČIAUSIA',
    phantomBadge: 'REKOMENDUOJAMA',
    trustBadge: 'BE DOKUMENTŲ',
    revolutBadge: 'TIESIAI IŠ BANKO',
    exactSolWarning: 'SVARBU: išsiųskite tiksliai jūsų krepšeliui sugeneruotą SOL sumą. Išsiuntus netikslią sumą, užsakymas nebus patvirtintas.',
    howTo: 'Kaip?',
    // Swaps guide
    swapsTitle: 'Swaps.app — greičiausias būdas',
    swapsDesc: 'Pirkite ir išsiųskite SOL vienu mygtuku — jokio wallet nereikia',
    swapsStep1T: 'Atidarykite Swaps.app',
    swapsStep1D: 'Spauskite "Pereiti prie apmokėjimo" krepšelyje. Sistema automatiškai atdarys Swaps.app su iš anksto užpildyta suma ir mūsų adresu.',
    swapsStep1Ok: 'Nereikia sukurti paskyros ar atsisiųsti programėlės.',
    swapsStep2T: 'Pasirinkite mokėjimo metodą',
    swapsStep2D: 'Galite mokėti Apple Pay, Google Pay arba kortele. Suma užpildyta automatiškai.',
    swapsStep3T: 'Patvirtinkite mokėjimą',
    swapsStep3D: 'SOL bus automatiškai nupirktas ir išsiųstas tiesiai į mūsų adresą. Jums nieko papildomai daryti nereikia.',
    swapsStep3Ok: 'Mokėjimas patvirtinamas per kelias minutes.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — žingsniai',
    phantomDesc: 'Saugiausias ir populiariausias Solana wallet',
    phantomStep1T: 'Atsisiųskite Phantom',
    phantomStep1D: 'App Store arba Google Play — nemokama programėlė. Taip pat galima kaip Chrome naršyklės priedas.',
    phantomStep2T: 'Susikurkite piniginę',
    phantomStep2D: 'Spauskite "Create New Wallet". Išsaugokite 12 žodžių atkūrimo frazę saugioje vietoje.',
    phantomStep2W: 'Saugokite frazę — tai vienintelis būdas atkurti piniginę.',
    phantomStep3T: 'Nusipirkite SOL per Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). Provider sąraše pasirinkite Paybis — pirkimas be KYC. Mokėkite kortele arba Apple Pay. Pirkite ~5€ daugiau tinklo mokesčiams.',
    phantomStep3Ok: 'Paybis: greitas pirkimas be dokumento patvirtinimo.',
    phantomStep4T: 'Išsiųskite SOL mums',
    phantomStep4D: 'Phantom → pasirinkite SOL → "Send" → įklijuokite mūsų adresą → įveskite tikslią sumą ir patvirtinkite.',
    phantomStep4Ok: 'Mokėjimas įvyksta per kelias sekundes. Po mokėjimo sistema automatiškai patvirtins.',
    // Trust guide
    trustTitle: 'Trust Wallet — žingsniai',
    trustDesc: 'Populiari mobili piniginė su paprasta SOL pirkimo galimybe',
    trustStep1T: 'Atsisiųskite Trust Wallet',
    trustStep1D: 'App Store (iPhone) arba Google Play (Android) — 100% nemokama ir saugi programėlė.',
    trustStep2T: 'Sukurkite naują piniginę',
    trustStep2D: 'Spauskite "Create New Wallet". Išsaugokite slaptą frazę (Recovery Phrase) saugioje vietoje.',
    trustStep2W: 'Saugokite slaptą frazę — tai vienintelis būdas atkurti piniginę.',
    trustStep3T: 'Nusipirkite SOL be KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". Provider sąraše pasirinkite Paybis. Mokėkite Apple Pay arba kortele. Pirkite ~5€ daugiau tinklo mokesčiams.',
    trustStep3Ok: 'Paybis: pirkimas be tapatybės patvirtinimo.',
    trustStep4T: 'Išsiųskite SOL mums',
    trustStep4D: 'Trust Wallet → pasirinkite SOL → "Send" → įklijuokite mūsų adresą → įveskite tikslią sumą ir patvirtinkite.',
    trustStep4Ok: 'Mokėjimas įvyksta per kelias sekundes. Sistema automatiškai patvirtins.',
    // Revolut guide
    revolutTitle: 'Revolut — žingsniai',
    revolutDesc: 'Turite Revolut? Galite pirkti SOL tiesiai per programėlę',
    revolutStep1T: 'Atidarykite Revolut programėlę',
    revolutStep1D: 'Eikite į skyrių "Crypto". Jei neturite Revolut — atsisiųskite iš App Store arba Google Play.',
    revolutStep2T: 'Nusipirkite SOL',
    revolutStep2D: 'Crypto → ieškokite "Solana (SOL)" → "Buy". Pirkite ~5€ daugiau tinklo mokesčiams. Atsiskaitymas iš Revolut balanso.',
    revolutStep3T: 'Persiųskite SOL į mūsų adresą',
    revolutStep3D: 'Crypto skyriuje pasirinkite SOL → "Send" → "External wallet" → įklijuokite mūsų Solana adresą → įveskite tikslią sumą.',
    revolutStep3W: 'Pastaba: Revolut gali taikyti išvedimo į išorinį wallet ribojimus priklausomai nuo jūsų paskyros lygio.',
    revolutStep4T: 'Mokėjimas patvirtinamas automatiškai',
    revolutStep4D: 'Sistema patikrins mokėjimą ir patvirtins užsakymą. Jei kyla klausimų — susisiekite Telegram.',
    revolutStep4Ok: 'Po mokėjimo parašykite: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Turite klausimų?',
    ctaAnswer: 'Atsakome greitai ir paprastai.',
    ctaTelegram: 'Rašykite Telegram: @Peptidai',
    ctaOperating: 'Veikiame jau daugiau nei 6 mėnesius',
    // Footer
    footerContact: 'Susisiekite su mumis',
    footerCopy: '© 2025–2026 Peptidai Lietuva. Visi produktai skirti tyrimams.',
    // Toast
    addedToCart: 'pridėtas į krepšelį!',
    // Cart
    cartTitle: 'Krepšelis',
    cartEmpty: 'Jūsų krepšelis tuščias',
    cartContinue: 'Tęsti apsipirkimą',
    cartProducts: 'Produktai:',
    cartShipping: 'Pristatymas:',
    cartFree: 'NEMOKAMAS',
    cartFreeMsg: 'Nemokamas pristatymas nuo 50€!',
    cartFreeUntil: 'Dar {amount}€ iki nemokamo pristatymo',
    cartTotal: 'Viso:',
    cartPaySol: 'Mokėsite SOL:',
    cartRate: 'Kursas:',
    cartLoadingRate: 'Kraunamas kursas...',
    cartUpdated: 'Atnaujinta:',
    cartCheckout: 'Pereiti prie apmokėjimo',
    cartSecure: 'Saugus pirkimas',
    cartAnon: 'Anonimiškas',
    cartDays: '2–3 d. d.',
    cartPrice: 'Kaina:',
    cartQty: 'vnt',
    // Checkout
    checkoutDelivery: 'Pristatymo informacija',
    checkoutPayment: 'Apmokėjimas',
    checkoutPhone: 'Telefono numeris',
    checkoutCity: 'Miestas',
    checkoutSelectCity: 'Pasirinkite miestą',
    checkoutSelectLocker: 'Pasirinkite paštomatą',
    checkoutLockerCode: 'Paštomato kodas:',
    checkoutDiscount: 'Nuolaidos kodas (neprivaloma)',
    checkoutDiscountApplied: '{code} — {percent}% nuolaida',
    checkoutRemove: 'Pašalinti',
    checkoutEnterCode: 'Įveskite kodą',
    checkoutApply: 'Taikyti',
    checkoutDiscountError: 'Nuolaidos kodas nerastas arba nebegalioja.',
    checkoutCodeError: 'Klaida tikrinant kodą. Bandykite dar kartą.',
    checkoutProducts: 'Produktai:',
    checkoutDiscountLine: 'Nuolaida ({code}, {percent}%):',
    checkoutShipping: 'Pristatymas:',
    checkoutTotal: 'Viso:',
    checkoutContinue: 'Tęsti prie apmokėjimo',
    checkoutCreating: 'Kuriamas užsakymas...',
    checkoutConfirm: 'Patvirtinti mokėjimą {amount} SOL',
    checkoutSelectMethod: 'Pasirinkite apmokėjimo būdą',
    checkoutBack: 'Atgal',
    checkoutFreeShipping: 'Nemokamas pristatymas nuo 50€!',
    checkoutFreeShippingAdd: 'Pridėkite dar {amount}€ ir gaukite nemokamą pristatymą!',
    // Pending
    pendingTitle: 'Laukiama apmokėjimo',
    pendingOrder: 'Užsakymas',
    pendingChecking: 'Tikrinamas mokėjimas...',
    pendingNext: 'Kitas patikrinimas po {time}s — sistema tikrina automatiškai',
    pendingSend: 'Siųsti mokėjimą',
    pendingExact: 'Tiksliai siųsti sumą:',
    pendingCopy: 'Kopijuoti',
    pendingCopied: 'Nukopijuota',
    pendingAddress: 'Siųsti į adresą:',
    pendingWarning: 'Siųskite TIKSLIAI nurodytą sumą SOL',
    pendingContact: 'Netikslios sumos atveju susisiekite:',
    pendingClose: 'Uždaryti',
    // Success
    successTitle: 'Užsakymas sukurtas!',
    successOrderNum: 'Užsakymo numeris',
    successConfirmed: 'Mokėjimas gautas ir patvirtintas!',
    successConfirmedMsg: 'Puiku! Gavome jūsų mokėjimą. Pristatysime užsakymą į pasirinktą paštomatą kuo greičiau.',
    successAwaitingPayment: 'Laukiama mokėjimo',
    successNextCheck: 'Kitas patikrinimas po {time}s',
    successMakePayment: 'Atlikite mokėjimą SOL (Solana)',
    successPaymentAmount: 'Mokėjimo suma:',
    successBuySwaps: 'Pirkti {amount} SOL per Swaps.app',
    successImportant: 'Svarbu:',
    successBullet1Swaps: 'Spauskite mygtuką aukščiau ir pirkite TIKSLIAI {amount} SOL',
    successBullet2Swaps: 'SOL bus automatiškai išsiųstas į mūsų adresą',
    successBullet3: 'Po mokėjimo susisiekite su mumis Telegram',
    successBullet1: 'Siųskite TIKSLIAI {amount} SOL',
    successBullet2: 'Naudokite Solana tinklą',
    successOrderInfo: 'Užsakymo informacija:',
    successPurchased: 'Pirkta:',
    successPhone: 'Telefonas:',
    successCity: 'Miestas:',
    successLocker: 'Paštomatas:',
    successSubtotal: 'Produktų suma:',
    successDiscountCode: 'Nuolaidos kodas:',
    successDiscount: 'Nuolaida ({percent}%):',
    successShipping: 'Pristatymas:',
    successTotalPaid: 'Viso mokėta:',
    successContact: 'Jei turite klausimų apie savo užsakymą, susisiekite:',
    successFinish: 'Baigti',
    // Checkout guides
    guideSwapsFastest: 'GREIČIAUSIAS BŪDAS ATSISKAITYTI',
    guideSwapsFastestDesc: 'Pirkite ir išsiųskite SOL vienu mygtuku — jokio wallet nereikia',
    guideSwaps1T: 'Spauskite mygtuką žemiau',
    guideSwaps1B1: 'Atsidarys Swaps.app — paprasta SOL pirkimo platforma',
    guideSwaps1B2: 'Suma jau užpildyta automatiškai: {amount} SOL',
    guideSwaps1B3: 'Mūsų adresas jau įklijuotas — jums nieko papildomai daryti nereikia',
    guideSwaps2T: 'Apmokėkite kortele arba Apple Pay',
    guideSwaps2B1: 'Pasirinkite mokėjimo metodą: Apple Pay, Google Pay arba kortelę',
    guideSwaps2B2: 'Sumokėkite ≈ {amount}€ + nedidelis paslaugos mokestis',
    guideSwaps2B3: 'SOL bus automatiškai išsiųstas tiesiai į mūsų adresą',
    guideSwaps2Note: 'Nereikia jokio crypto wallet — mokate kaip už bet kurią preką internete',
    guideSwaps3T: 'Susisiekite su mumis Telegram',
    guideSwaps3B1: 'Po sėkmingo mokėjimo parašykite mums Telegram',
    guideSwaps3B2: 'Nurodykite savo užsakymo numerį',
    guideSwapsBtn: 'Atidaryti Swaps.app ir mokėti {amount} SOL',
    guideSolanaTitle: 'SOLANA APMOKEJIMO GIDAS',
    guideSolanaDesc: 'Tai saugiausias ir greičiausias būdas atsiskaityti',
    guidePhantom1T: 'Susikurkite Phantom wallet (2 min.)',
    guidePhantom1Desc: 'Rekomenduojame Phantom Wallet - paprasčiausia programėlė pradedantiesiems.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Atsisiųskite iš App Store arba Google Play arba Google Chrome Extension',
    guidePhantom1B1: 'Atsisiųskite iš App Store arba Google Play',
    guidePhantom1B2: 'Susikurkite naują wallet',
    guidePhantom1B3: 'SVARBU: Išsisaugokite 12 žodžių atkūrimo frazę (Seed Phrase)!',
    guidePhantom1B4: 'Nustatymuose Preferences pakeiskite valiutą iš $ į €',
    guidePhantom2T: 'Nusipirkite SOL tiesiai per Phantom',
    guidePhantom2B1: 'Spauskite "Buy" ir pasirinkite Solana (SOL)',
    guidePhantom2B2: 'Įveskite sumą: ~{amount}€ (pirkite ~5€ daugiau tinklo mokesčiams)',
    guidePhantom2B3: 'Provider sąraše spauskite "Fund Your Wallet"',
    guidePhantom2B4: 'Pasirinkite Solana (SOL)',
    guidePhantom2B5: 'Vietoj MoonPay pakeiskite provider į Paybis — nereikia dokumento patvirtinimo',
    guidePhantom2B6: 'Atsiskaityti galima: kortele arba Apple Pay',
    guidePhantom2Note: 'Paybis: greitas pirkimas be KYC dokumento patikrinimo',
    guidePhantom3T: 'Išsiųskite SOL mums',
    guidePhantom3B1: 'Phantom wallet pasirinkite Solana',
    guidePhantom3B2: 'Spauskite "Send All"',
    guidePhantom3B3: 'Įklijuokite mūsų adresą',
    guidePhantom3B4: 'Siųsite sumą: {amount} SOL',
    guidePhantom3Note: 'Po siuntimo parašykite mums Telegram: @Peptidai',
    guideTrustTitle: 'PIRKIMAS BE DOKUMENTO (KYC)',
    guideTrustDesc: 'Naudokite Apple Pay arba kortelę — greitai ir paprastai',
    guideTrust1T: 'Atsisiųskite Trust Wallet',
    guideTrust1B1: 'Eikite į App Store arba Google Play',
    guideTrust1B2: 'Atsisiųskite "Trust Wallet" programėlę',
    guideTrust1B3: 'Susikurkite naują wallet ir išsisaugokite Seed Phrase',
    guideTrust2T: 'Nusipirkite SOL — spauskite "Fund Your Wallet"',
    guideTrust2B1: 'Spauskite "Buy" mygtuką programėlėje',
    guideTrust2B2: 'Pasirinkite Solana (SOL)',
    guideTrust2B3: 'Spauskite "Fund Your Wallet"',
    guideTrust2B4: 'Pasirinkite mokėjimo metodą: Apple Pay',
    guideTrust2B5: 'Provider sąraše raskite ir pakeiskite MoonPay į Paybis',
    guideTrust2B6: 'Įveskite sumą: ~{amount}€ ir apmokėkite',
    guideTrust2Note: 'Paybis — pirkimas be KYC dokumento patikrinimo',
    guideTrust3T: 'Išsiųskite SOL mums',
    guideTrust3B1: 'Pasirinkite SOL savo paskyroje',
    guideTrust3B2: 'Spauskite "Send"',
    guideTrust3B3: 'Įklijuokite mūsų wallet adresą',
    guideTrust3B4: 'Įveskite sumą: {amount} SOL',
    guideTrust3B5: 'Patvirtinkite siuntimą',
    guideTrust3Note: 'Po mokėjimo parašykite: @Peptidai (Telegram)',
    guideRevolut1T: 'Atidarykite Revolut programėlę',
    guideRevolut1B1: 'Eikite į Revolut programėlę',
    guideRevolut1B2: 'Jei neturite - atsisiųskite iš App Store / Google Play',
    guideRevolut2T: 'Nusipirkite SOL per Revolut',
    guideRevolut2B1: 'Eikite į skyrių "Crypto"',
    guideRevolut2B2: 'Ieškokite Solana (SOL)',
    guideRevolut2B3: 'Spauskite "Buy"',
    guideRevolut2B4: 'Pirkite ~{amount}€ vertės SOL',
    guideRevolut3T: 'Persiųskite SOL į mūsų adresą',
    guideRevolut3B1: 'Crypto skyriuje pasirinkite SOL',
    guideRevolut3B2: 'Spauskite "Send" arba "Transfer"',
    guideRevolut3B3: 'Pasirinkite "External wallet"',
    guideRevolut3B4: 'Įveskite mūsų Solana adresą',
    guideRevolut3B5: 'Įveskite sumą: {amount} SOL',
    guideRevolutWarn: 'Pastaba: Revolut gali taikyti pervedimo į išorinį wallet ribojimus priklausomai nuo jūsų paskyros lygio.',
    guideRevolutNote: 'Po mokėjimo parašykite: @Peptidai (Telegram)',
    // ProductCard
    details: 'Detaliau',
    addToCart: 'Į krepšelį',
    // ProductDetail
    description: 'Aprašymas',
    selectQty: 'Pasirinkite kiekį',
    price: 'Kaina',
    delivery: 'Pristatymas',
    deliveryTime: 'Per 2-3 dienas',
    addToCartBtn: 'Pridėti į krepšelį',
    total: 'Viso:',
    freeShipping: 'NEMOKAMAS',
    paymentInfo: 'Mokėjimo informacija',
    exactSendAmount: 'Tiksliai siųsti sumą:',
    sendToAddress: 'Siųsti į adresą:',
    sendExact: 'Siųskite TIKSLIAI nurodytą sumą',
    orderAmount: 'Užsakymo suma',
    paymentMethodSol: 'Mokėjimas Solana (SOL)',
    exactAmountNote: 'Tikslus kiekis bus nurodytas apmokėjimo žingsnyje',
    errorTitle: 'Klaida:',
  },
  en: {
    // Header
    cart: 'Cart',
    // Hero
    heroSubtitle: 'Highest quality peptides. Trusted seller in Lithuania for over half a year.',
    heroStat1: 'Hundreds of satisfied customers',
    heroStat2: 'Fast delivery across Lithuania',
    heroStat3: '100% anonymous purchase',
    productsTitle: 'Products',
    loading: 'Loading products...',
    // About
    aboutTitle: 'About us',
    aboutSubtitle: 'The most trusted Peptides & Steroids store in Lithuania',
    aboutText1: 'Since 2025 we have been providing the highest quality peptides to Lithuanian customers.',
    aboutText2: 'In this time we have earned the trust of hundreds of customers. Each product is carefully checked and shipped, ensuring discreet and fast delivery.',
    aboutSlogan: 'Peptides — the medicine of the future.',
    stat1Title: 'Working since 2025',
    stat1Desc: 'Experience and customer trust',
    stat2Title: 'Shipping 2-3 days',
    stat2Desc: 'Across Lithuania to parcel lockers',
    stat3Title: 'Anonymous purchase',
    stat3Desc: 'Your privacy — our priority',
    // Payment info
    paymentTitle: '100% Anonymous Cryptocurrency Payment',
    paymentSubtitle: 'No KYC, no identity verification',
    payBadge1: 'No KYC',
    payBadge1Sub: 'No documents needed',
    payBadge2: 'Anonymous',
    payBadge2Sub: '100% private',
    payBadge3: 'Fast',
    payBadge3Sub: 'A few seconds',
    payBadge4: 'Secure',
    payBadge4Sub: 'In your control',
    choosePayment: 'Choose payment method — all 100% anonymous',
    swapsBadge: 'FASTEST',
    phantomBadge: 'RECOMMENDED',
    trustBadge: 'NO DOCUMENTS',
    revolutBadge: 'DIRECT FROM BANK',
    exactSolWarning: 'IMPORTANT: send exactly the SOL amount generated for your cart. If the wrong amount is sent, the order will not be confirmed.',
    howTo: 'How?',
    // Swaps guide
    swapsTitle: 'Swaps.app — fastest method',
    swapsDesc: 'Buy and send SOL with one button — no wallet needed',
    swapsStep1T: 'Open Swaps.app',
    swapsStep1D: 'Click "Proceed to checkout" in the cart. The system will automatically open Swaps.app with the pre-filled amount and our address.',
    swapsStep1Ok: 'No need to create an account or download an app.',
    swapsStep2T: 'Choose payment method',
    swapsStep2D: 'You can pay with Apple Pay, Google Pay or card. Amount is filled automatically.',
    swapsStep3T: 'Confirm payment',
    swapsStep3D: 'SOL will be automatically purchased and sent directly to our address. You don\'t need to do anything extra.',
    swapsStep3Ok: 'Payment confirmed within a few minutes.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — steps',
    phantomDesc: 'Safest and most popular Solana wallet',
    phantomStep1T: 'Download Phantom',
    phantomStep1D: 'App Store or Google Play — free app. Also available as Chrome extension.',
    phantomStep2T: 'Create a wallet',
    phantomStep2D: 'Click "Create New Wallet". Save the 12-word recovery phrase in a safe place.',
    phantomStep2W: 'Guard the phrase — it\'s the only way to restore the wallet.',
    phantomStep3T: 'Buy SOL through Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). In the provider list select Paybis — no KYC purchase. Pay with card or Apple Pay. Buy ~€5 more for network fees.',
    phantomStep3Ok: 'Paybis: fast purchase without document verification.',
    phantomStep4T: 'Send SOL to us',
    phantomStep4D: 'Phantom → select SOL → "Send" → paste our address → enter the exact amount and confirm.',
    phantomStep4Ok: 'Payment happens within seconds. System will auto-confirm after payment.',
    // Trust guide
    trustTitle: 'Trust Wallet — steps',
    trustDesc: 'Popular mobile wallet with easy SOL purchase',
    trustStep1T: 'Download Trust Wallet',
    trustStep1D: 'App Store (iPhone) or Google Play (Android) — 100% free and safe app.',
    trustStep2T: 'Create a new wallet',
    trustStep2D: 'Click "Create New Wallet". Save the secret phrase (Recovery Phrase) in a safe place.',
    trustStep2W: 'Guard the secret phrase — it\'s the only way to restore the wallet.',
    trustStep3T: 'Buy SOL without KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". In the provider list select Paybis. Pay with Apple Pay or card. Buy ~€5 more for network fees.',
    trustStep3Ok: 'Paybis: purchase without identity verification.',
    trustStep4T: 'Send SOL to us',
    trustStep4D: 'Trust Wallet → select SOL → "Send" → paste our address → enter the exact amount and confirm.',
    trustStep4Ok: 'Payment happens within seconds. System will auto-confirm.',
    // Revolut guide
    revolutTitle: 'Revolut — steps',
    revolutDesc: 'Have Revolut? You can buy SOL directly through the app',
    revolutStep1T: 'Open the Revolut app',
    revolutStep1D: 'Go to the "Crypto" section. If you don\'t have Revolut — download from App Store or Google Play.',
    revolutStep2T: 'Buy SOL',
    revolutStep2D: 'Crypto → search "Solana (SOL)" → "Buy". Buy ~€5 more for network fees. Payment from Revolut balance.',
    revolutStep3T: 'Transfer SOL to our address',
    revolutStep3D: 'In the Crypto section select SOL → "Send" → "External wallet" → paste our Solana address → enter exact amount.',
    revolutStep3W: 'Note: Revolut may apply withdrawal to external wallet restrictions depending on your account level.',
    revolutStep4T: 'Payment confirmed automatically',
    revolutStep4D: 'The system will check payment and confirm the order. If you have questions — contact Telegram.',
    revolutStep4Ok: 'After payment write: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Have questions?',
    ctaAnswer: 'We reply quickly, simply and discreetly.',
    ctaTelegram: 'Write Telegram: @Peptidai',
    ctaOperating: 'Operating for over 6 months',
    // Footer
    footerContact: 'Contact us',
    footerCopy: '© 2025–2026 Peptidai Lietuva. All products intended for research and sports.',
    // Toast
    addedToCart: 'added to cart!',
    // Cart
    cartTitle: 'Cart',
    cartEmpty: 'Your cart is empty',
    cartContinue: 'Continue shopping',
    cartProducts: 'Products:',
    cartShipping: 'Shipping:',
    cartFree: 'FREE',
    cartFreeMsg: 'Free shipping from €50!',
    cartFreeUntil: 'Another {amount}€ until free shipping',
    cartTotal: 'Total:',
    cartPaySol: 'You will pay SOL:',
    cartRate: 'Rate:',
    cartLoadingRate: 'Loading rate...',
    cartUpdated: 'Updated:',
    cartCheckout: 'Proceed to checkout',
    cartSecure: 'Secure purchase',
    cartAnon: 'Anonymous',
    cartDays: '2–3 days',
    cartPrice: 'Price:',
    cartQty: 'pcs',
    // Checkout
    checkoutDelivery: 'Delivery information',
    checkoutPayment: 'Payment',
    checkoutPhone: 'Phone number',
    checkoutCity: 'City',
    checkoutSelectCity: 'Select city',
    checkoutSelectLocker: 'Select parcel locker',
    checkoutLockerCode: 'Locker code:',
    checkoutDiscount: 'Discount code (optional)',
    checkoutDiscountApplied: '{code} — {percent}% discount',
    checkoutRemove: 'Remove',
    checkoutEnterCode: 'Enter code',
    checkoutApply: 'Apply',
    checkoutDiscountError: 'Discount code not found or expired.',
    checkoutCodeError: 'Error checking code. Please try again.',
    checkoutProducts: 'Products:',
    checkoutDiscountLine: 'Discount ({code}, {percent}%):',
    checkoutShipping: 'Shipping:',
    checkoutTotal: 'Total:',
    checkoutContinue: 'Continue to payment',
    checkoutCreating: 'Creating order...',
    checkoutConfirm: 'Confirm payment {amount} SOL',
    checkoutSelectMethod: 'Select payment method',
    checkoutBack: 'Back',
    checkoutFreeShipping: 'Free shipping from €50!',
    checkoutFreeShippingAdd: 'Add {amount}€ more for free shipping!',
    // Pending
    pendingTitle: 'Awaiting payment',
    pendingOrder: 'Order',
    pendingChecking: 'Checking payment...',
    pendingNext: 'Next check in {time}s — system checks automatically',
    pendingSend: 'Send payment',
    pendingExact: 'Send exact amount:',
    pendingCopy: 'Copy',
    pendingCopied: 'Copied',
    pendingAddress: 'Send to address:',
    pendingWarning: 'Send EXACTLY the specified SOL amount',
    pendingContact: 'If incorrect amount — contact:',
    pendingClose: 'Close',
    // Success
    successTitle: 'Order created!',
    successOrderNum: 'Order number',
    successConfirmed: 'Payment received and confirmed!',
    successConfirmedMsg: 'Great! We received your payment. We will deliver your order to the selected parcel locker as soon as possible.',
    successAwaitingPayment: 'Awaiting payment',
    successNextCheck: 'Next check in {time}s',
    successMakePayment: 'Make payment in SOL (Solana)',
    successPaymentAmount: 'Payment amount:',
    successBuySwaps: 'Buy {amount} SOL via Swaps.app',
    successImportant: 'Important:',
    successBullet1Swaps: 'Click the button above and buy EXACTLY {amount} SOL',
    successBullet2Swaps: 'SOL will be automatically sent to our address',
    successBullet3: 'Contact us via Telegram after payment',
    successBullet1: 'Send EXACTLY {amount} SOL',
    successBullet2: 'Use the Solana network',
    successOrderInfo: 'Order information:',
    successPurchased: 'Purchased:',
    successPhone: 'Phone:',
    successCity: 'City:',
    successLocker: 'Locker:',
    successSubtotal: 'Products total:',
    successDiscountCode: 'Discount code:',
    successDiscount: 'Discount ({percent}%):',
    successShipping: 'Shipping:',
    successTotalPaid: 'Total paid:',
    successContact: 'If you have questions about your order, contact:',
    successFinish: 'Finish',
    // Checkout guides
    guideSwapsFastest: 'FASTEST WAY TO PAY',
    guideSwapsFastestDesc: 'Buy and send SOL with one button — no wallet needed',
    guideSwaps1T: 'Click the button below',
    guideSwaps1B1: 'Swaps.app will open — a simple SOL purchase platform',
    guideSwaps1B2: 'Amount already auto-filled: {amount} SOL',
    guideSwaps1B3: 'Our address is already pasted — you don\'t need to do anything extra',
    guideSwaps2T: 'Pay with card or Apple Pay',
    guideSwaps2B1: 'Select payment method: Apple Pay, Google Pay or card',
    guideSwaps2B2: 'Pay ≈ {amount}€ + small service fee',
    guideSwaps2B3: 'SOL will be automatically sent directly to our address',
    guideSwaps2Note: 'No crypto wallet needed — pay like any online purchase',
    guideSwaps3T: 'Contact us via Telegram',
    guideSwaps3B1: 'After successful payment write us on Telegram',
    guideSwaps3B2: 'Provide your order number',
    guideSwapsBtn: 'Open Swaps.app and pay {amount} SOL',
    guideSolanaTitle: 'SOLANA PAYMENT GUIDE',
    guideSolanaDesc: 'This is the safest and fastest way to pay',
    guidePhantom1T: 'Create Phantom wallet (2 min.)',
    guidePhantom1Desc: 'We recommend Phantom Wallet — the simplest app for beginners.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Download from App Store or Google Play or Google Chrome Extension',
    guidePhantom1B1: 'Download from App Store or Google Play',
    guidePhantom1B2: 'Create a new wallet',
    guidePhantom1B3: 'IMPORTANT: Save the 12-word recovery phrase (Seed Phrase)!',
    guidePhantom1B4: 'In Settings → Preferences change currency from $ to €',
    guidePhantom2T: 'Buy SOL directly through Phantom',
    guidePhantom2B1: 'Click "Buy" and select Solana (SOL)',
    guidePhantom2B2: 'Enter amount: ~{amount}€ (buy ~€5 more for network fees)',
    guidePhantom2B3: 'In the provider list click "Fund Your Wallet"',
    guidePhantom2B4: 'Select Solana (SOL)',
    guidePhantom2B5: 'Instead of MoonPay switch provider to Paybis — no document verification',
    guidePhantom2B6: 'Can pay with: card or Apple Pay',
    guidePhantom2Note: 'Paybis: fast purchase without KYC document verification',
    guidePhantom3T: 'Send SOL to us',
    guidePhantom3B1: 'In Phantom wallet select Solana',
    guidePhantom3B2: 'Click "Send All"',
    guidePhantom3B3: 'Paste our address',
    guidePhantom3B4: 'Amount to send: {amount} SOL',
    guidePhantom3Note: 'After sending write us on Telegram: @Peptidai',
    guideTrustTitle: 'PURCHASE WITHOUT DOCUMENT (KYC)',
    guideTrustDesc: 'Use Apple Pay or card — fast and simple',
    guideTrust1T: 'Download Trust Wallet',
    guideTrust1B1: 'Go to App Store or Google Play',
    guideTrust1B2: 'Download the "Trust Wallet" app',
    guideTrust1B3: 'Create a new wallet and save the Seed Phrase',
    guideTrust2T: 'Buy SOL — click "Fund Your Wallet"',
    guideTrust2B1: 'Click the "Buy" button in the app',
    guideTrust2B2: 'Select Solana (SOL)',
    guideTrust2B3: 'Click "Fund Your Wallet"',
    guideTrust2B4: 'Select payment method: Apple Pay',
    guideTrust2B5: 'In provider list find and change MoonPay to Paybis',
    guideTrust2B6: 'Enter amount: ~{amount}€ and pay',
    guideTrust2Note: 'Paybis — purchase without KYC document verification',
    guideTrust3T: 'Send SOL to us',
    guideTrust3B1: 'Select SOL in your account',
    guideTrust3B2: 'Click "Send"',
    guideTrust3B3: 'Paste our wallet address',
    guideTrust3B4: 'Enter amount: {amount} SOL',
    guideTrust3B5: 'Confirm the transfer',
    guideTrust3Note: 'After payment write: @Peptidai (Telegram)',
    guideRevolut1T: 'Open the Revolut app',
    guideRevolut1B1: 'Go to the Revolut app',
    guideRevolut1B2: 'If you don\'t have it — download from App Store / Google Play',
    guideRevolut2T: 'Buy SOL through Revolut',
    guideRevolut2B1: 'Go to the "Crypto" section',
    guideRevolut2B2: 'Search for Solana (SOL)',
    guideRevolut2B3: 'Click "Buy"',
    guideRevolut2B4: 'Buy ~{amount}€ worth of SOL',
    guideRevolut3T: 'Transfer SOL to our address',
    guideRevolut3B1: 'In the Crypto section select SOL',
    guideRevolut3B2: 'Click "Send" or "Transfer"',
    guideRevolut3B3: 'Select "External wallet"',
    guideRevolut3B4: 'Enter our Solana address',
    guideRevolut3B5: 'Enter amount: {amount} SOL',
    guideRevolutWarn: 'Note: Revolut may apply transfer to external wallet restrictions depending on your account level.',
    guideRevolutNote: 'After payment write: @Peptidai (Telegram)',
    // ProductCard
    details: 'Details',
    addToCart: 'Add to cart',
    // ProductDetail
    description: 'Description',
    selectQty: 'Select quantity',
    price: 'Price',
    delivery: 'Delivery',
    deliveryTime: 'Within 2-3 days',
    addToCartBtn: 'Add to cart',
    total: 'Total:',
    freeShipping: 'FREE',
    paymentInfo: 'Payment information',
    exactSendAmount: 'Send exact amount:',
    sendToAddress: 'Send to address:',
    sendExact: 'Send EXACTLY the specified amount',
    orderAmount: 'Order amount',
    paymentMethodSol: 'Payment via Solana (SOL)',
    exactAmountNote: 'Exact amount will be shown in the payment step',
    errorTitle: 'Error:',
  },
  ru: {
    // Header
    cart: 'Корзина',
    // Hero
    heroSubtitle: 'Пептиды высочайшего качества. Проверенный продавец в Литве уже более полугода.',
    heroStat1: 'Сотни довольных клиентов',
    heroStat2: 'Быстрая доставка по всей Литве',
    heroStat3: '100% анонимная покупка',
    productsTitle: 'Товары',
    loading: 'Загрузка товаров...',
    // About
    aboutTitle: 'О нас',
    aboutSubtitle: 'Самый надёжный магазин пептидов и стероидов в Литве',
    aboutText1: 'С 2025 года мы предоставляем пептиды высочайшего качества клиентам Литвы.',
    aboutText2: 'За это время мы завоевали доверие сотен клиентов. Каждый товар тщательно проверяется и упаковывается, обеспечивая дискретную и быструю доставку.',
    aboutSlogan: 'Пептиды — медицина будущего.',
    stat1Title: 'Работаем с 2025г.',
    stat1Desc: 'Опыт и доверие клиентов',
    stat2Title: 'Доставка 2-3 дня',
    stat2Desc: 'По всей Литве в постоматы',
    stat3Title: 'Анонимная покупка',
    stat3Desc: 'Ваша конфиденциальность — наш приоритет',
    // Payment info
    paymentTitle: '100% Анонимная оплата криптовалютой',
    paymentSubtitle: 'Без KYC, без верификации личности',
    payBadge1: 'Без KYC',
    payBadge1Sub: 'Документы не нужны',
    payBadge2: 'Анонимно',
    payBadge2Sub: '100% приватно',
    payBadge3: 'Быстро',
    payBadge3Sub: 'Несколько секунд',
    payBadge4: 'Безопасно',
    payBadge4Sub: 'Под вашим контролем',
    choosePayment: 'Выберите способ оплаты — все 100% анонимны',
    swapsBadge: 'БЫСТРЕЕ ВСЕГО',
    phantomBadge: 'РЕКОМЕНДУЕМ',
    trustBadge: 'БЕЗ ДОКУМЕНТОВ',
    revolutBadge: 'ПРЯМО ИЗ БАНКА',
    exactSolWarning: 'ВАЖНО: отправьте точно ту сумму SOL, которая была сгенерирована для вашей корзины. При неточной сумме заказ не будет подтверждён.',
    howTo: 'Как?',
    // Swaps guide
    swapsTitle: 'Swaps.app — самый быстрый способ',
    swapsDesc: 'Купите и отправьте SOL одной кнопкой — кошелёк не нужен',
    swapsStep1T: 'Откройте Swaps.app',
    swapsStep1D: 'Нажмите "Перейти к оплате" в корзине. Система автоматически откроет Swaps.app с предзаполненной суммой и нашим адресом.',
    swapsStep1Ok: 'Не нужно создавать аккаунт или скачивать приложение.',
    swapsStep2T: 'Выберите способ оплаты',
    swapsStep2D: 'Можно оплатить через Apple Pay, Google Pay или картой. Сумма заполнена автоматически.',
    swapsStep3T: 'Подтвердите оплату',
    swapsStep3D: 'SOL будет автоматически куплен и отправлен прямо на наш адрес. Вам больше ничего делать не нужно.',
    swapsStep3Ok: 'Оплата подтверждается в течение нескольких минут.',
    // Phantom guide
    phantomTitle: 'Phantom Wallet — шаги',
    phantomDesc: 'Самый безопасный и популярный Solana кошелёк',
    phantomStep1T: 'Скачайте Phantom',
    phantomStep1D: 'App Store или Google Play — бесплатное приложение. Также доступно как расширение Chrome.',
    phantomStep2T: 'Создайте кошелёк',
    phantomStep2D: 'Нажмите "Create New Wallet". Сохраните 12-словную фразу восстановления в надёжном месте.',
    phantomStep2W: 'Сохраните фразу — это единственный способ восстановить кошелёк.',
    phantomStep3T: 'Купите SOL через Phantom',
    phantomStep3D: 'Phantom → "Buy" → Solana (SOL). В списке провайдеров выберите Paybis — покупка без KYC. Оплата картой или Apple Pay. Купите ~€5 больше на комиссии сети.',
    phantomStep3Ok: 'Paybis: быстрая покупка без верификации документов.',
    phantomStep4T: 'Отправьте SOL нам',
    phantomStep4D: 'Phantom → выберите SOL → "Send" → вставьте наш адрес → введите точную сумму и подтвердите.',
    phantomStep4Ok: 'Оплата занимает несколько секунд. Система автоматически подтвердит после оплаты.',
    // Trust guide
    trustTitle: 'Trust Wallet — шаги',
    trustDesc: 'Популярный мобильный кошелёк с простой покупкой SOL',
    trustStep1T: 'Скачайте Trust Wallet',
    trustStep1D: 'App Store (iPhone) или Google Play (Android) — 100% бесплатное и безопасное приложение.',
    trustStep2T: 'Создайте новый кошелёк',
    trustStep2D: 'Нажмите "Create New Wallet". Сохраните секретную фразу (Recovery Phrase) в надёжном месте.',
    trustStep2W: 'Сохраните секретную фразу — это единственный способ восстановить кошелёк.',
    trustStep3T: 'Купите SOL без KYC',
    trustStep3D: 'Trust Wallet → "Buy" → Solana (SOL) → "Fund Your Wallet". В списке провайдеров выберите Paybis. Оплата Apple Pay или картой. Купите ~€5 больше на комиссии сети.',
    trustStep3Ok: 'Paybis: покупка без верификации личности.',
    trustStep4T: 'Отправьте SOL нам',
    trustStep4D: 'Trust Wallet → выберите SOL → "Send" → вставьте наш адрес → введите точную сумму и подтвердите.',
    trustStep4Ok: 'Оплата занимает несколько секунд. Система автоматически подтвердит.',
    // Revolut guide
    revolutTitle: 'Revolut — шаги',
    revolutDesc: 'Есть Revolut? Можете купить SOL прямо через приложение',
    revolutStep1T: 'Откройте приложение Revolut',
    revolutStep1D: 'Перейдите в раздел "Crypto". Если нет Revolut — скачайте из App Store или Google Play.',
    revolutStep2T: 'Купите SOL',
    revolutStep2D: 'Crypto → ищите "Solana (SOL)" → "Buy". Купите ~€5 больше на комиссии сети. Оплата с баланса Revolut.',
    revolutStep3T: 'Переведите SOL на наш адрес',
    revolutStep3D: 'В разделе Crypto выберите SOL → "Send" → "External wallet" → вставьте наш Solana адрес → введите точную сумму.',
    revolutStep3W: 'Примечание: Revolut может применять ограничения на вывод во внешний кошелёк в зависимости от уровня вашего аккаунта.',
    revolutStep4T: 'Оплата подтверждается автоматически',
    revolutStep4D: 'Система проверит оплату и подтвердит заказ. Если есть вопросы — свяжитесь через Telegram.',
    revolutStep4Ok: 'После оплаты напишите: @Peptidai (Telegram).',
    // Contact / CTA
    ctaQuestion: 'Есть вопросы?',
    ctaAnswer: 'Отвечаем быстро, просто и дискретно.',
    ctaTelegram: 'Пишите в Telegram: @Peptidai',
    ctaOperating: 'Работаем уже более 6 месяцев',
    // Footer
    footerContact: 'Свяжитесь с нами',
    footerCopy: '© 2025–2026 Peptidai Lietuva. Все товары предназначены для исследований и спорта.',
    // Toast
    addedToCart: 'добавлен в корзину!',
    // Cart
    cartTitle: 'Корзина',
    cartEmpty: 'Ваша корзина пуста',
    cartContinue: 'Продолжить покупки',
    cartProducts: 'Товары:',
    cartShipping: 'Доставка:',
    cartFree: 'БЕСПЛАТНО',
    cartFreeMsg: 'Бесплатная доставка от 50€!',
    cartFreeUntil: 'Ещё {amount}€ до бесплатной доставки',
    cartTotal: 'Итого:',
    cartPaySol: 'Вы заплатите SOL:',
    cartRate: 'Курс:',
    cartLoadingRate: 'Загрузка курса...',
    cartUpdated: 'Обновлено:',
    cartCheckout: 'Перейти к оплате',
    cartSecure: 'Безопасная покупка',
    cartAnon: 'Анонимно',
    cartDays: '2–3 дня',
    cartPrice: 'Цена:',
    cartQty: 'шт',
    // Checkout
    checkoutDelivery: 'Информация о доставке',
    checkoutPayment: 'Оплата',
    checkoutPhone: 'Номер телефона',
    checkoutCity: 'Город',
    checkoutSelectCity: 'Выберите город',
    checkoutSelectLocker: 'Выберите постомат',
    checkoutLockerCode: 'Код постомата:',
    checkoutDiscount: 'Код скидки (необязательно)',
    checkoutDiscountApplied: '{code} — скидка {percent}%',
    checkoutRemove: 'Удалить',
    checkoutEnterCode: 'Введите код',
    checkoutApply: 'Применить',
    checkoutDiscountError: 'Код скидки не найден или недействителен.',
    checkoutCodeError: 'Ошибка проверки кода. Попробуйте ещё раз.',
    checkoutProducts: 'Товары:',
    checkoutDiscountLine: 'Скидка ({code}, {percent}%):',
    checkoutShipping: 'Доставка:',
    checkoutTotal: 'Итого:',
    checkoutContinue: 'Перейти к оплате',
    checkoutCreating: 'Создание заказа...',
    checkoutConfirm: 'Подтвердить оплату {amount} SOL',
    checkoutSelectMethod: 'Выберите способ оплаты',
    checkoutBack: 'Назад',
    checkoutFreeShipping: 'Бесплатная доставка от 50€!',
    checkoutFreeShippingAdd: 'Добавьте ещё {amount}€ для бесплатной доставки!',
    // Pending
    pendingTitle: 'Ожидание оплаты',
    pendingOrder: 'Заказ',
    pendingChecking: 'Проверка оплаты...',
    pendingNext: 'Следующая проверка через {time}с — система проверяет автоматически',
    pendingSend: 'Отправить оплату',
    pendingExact: 'Отправить точную сумму:',
    pendingCopy: 'Копировать',
    pendingCopied: 'Скопировано',
    pendingAddress: 'Отправить на адрес:',
    pendingWarning: 'Отправьте ТОЧНО указанную сумму SOL',
    pendingContact: 'При неточной сумме свяжитесь:',
    pendingClose: 'Закрыть',
    // Success
    successTitle: 'Заказ создан!',
    successOrderNum: 'Номер заказа',
    successConfirmed: 'Оплата получена и подтверждена!',
    successConfirmedMsg: 'Отлично! Мы получили ваш платёж. Доставим заказ в выбранный постамат как можно скорее.',
    successAwaitingPayment: 'Ожидание оплаты',
    successNextCheck: 'Следующая проверка через {time}с',
    successMakePayment: 'Произведите оплату SOL (Solana)',
    successPaymentAmount: 'Сумма оплаты:',
    successBuySwaps: 'Купить {amount} SOL через Swaps.app',
    successImportant: 'Важно:',
    successBullet1Swaps: 'Нажмите кнопку выше и купите ТОЧНО {amount} SOL',
    successBullet2Swaps: 'SOL будет автоматически отправлен на наш адрес',
    successBullet3: 'После оплаты свяжитесь с нами через Telegram',
    successBullet1: 'Отправьте ТОЧНО {amount} SOL',
    successBullet2: 'Используйте сеть Solana',
    successOrderInfo: 'Информация о заказе:',
    successPurchased: 'Куплено:',
    successPhone: 'Телефон:',
    successCity: 'Город:',
    successLocker: 'Постомат:',
    successSubtotal: 'Сумма товаров:',
    successDiscountCode: 'Код скидки:',
    successDiscount: 'Скидка ({percent}%):',
    successShipping: 'Доставка:',
    successTotalPaid: 'Итого оплачено:',
    successContact: 'Если у вас есть вопросы по заказу, свяжитесь:',
    successFinish: 'Завершить',
    // Checkout guides
    guideSwapsFastest: 'САМЫЙ БЫСТРЫЙ СПОСОБ ОПЛАТЫ',
    guideSwapsFastestDesc: 'Купите и отправьте SOL одной кнопкой — кошелёк не нужен',
    guideSwaps1T: 'Нажмите кнопку ниже',
    guideSwaps1B1: 'Откроется Swaps.app — простая платформа покупки SOL',
    guideSwaps1B2: 'Сумма уже заполнена автоматически: {amount} SOL',
    guideSwaps1B3: 'Наш адрес уже вставлен — вам больше ничего делать не нужно',
    guideSwaps2T: 'Оплатите картой или Apple Pay',
    guideSwaps2B1: 'Выберите способ оплаты: Apple Pay, Google Pay или карту',
    guideSwaps2B2: 'Заплатите ≈ {amount}€ + небольшая комиссия',
    guideSwaps2B3: 'SOL будет автоматически отправлен прямо на наш адрес',
    guideSwaps2Note: 'Крипто кошелёк не нужен — платите как за любой онлайн-товар',
    guideSwaps3T: 'Свяжитесь с нами через Telegram',
    guideSwaps3B1: 'После успешной оплаты напишите нам в Telegram',
    guideSwaps3B2: 'Укажите номер своего заказа',
    guideSwapsBtn: 'Открыть Swaps.app и оплатить {amount} SOL',
    guideSolanaTitle: 'РУКОВОДСТВО ПО ОПЛАТЕ SOLANA',
    guideSolanaDesc: 'Это самый безопасный и быстрый способ оплаты',
    guidePhantom1T: 'Создайте Phantom кошелёк (2 мин.)',
    guidePhantom1Desc: 'Рекомендуем Phantom Wallet — самое простое приложение для начинающих.',
    guidePhantomAppName: 'Phantom - Crypto Wallet',
    guidePhantomDownload: 'Скачайте из App Store, Google Play или как расширение Chrome',
    guidePhantom1B1: 'Скачайте из App Store или Google Play',
    guidePhantom1B2: 'Создайте новый кошелёк',
    guidePhantom1B3: 'ВАЖНО: Сохраните 12-словную фразу восстановления (Seed Phrase)!',
    guidePhantom1B4: 'В Настройках → Preferences измените валюту с $ на €',
    guidePhantom2T: 'Купите SOL прямо через Phantom',
    guidePhantom2B1: 'Нажмите "Buy" и выберите Solana (SOL)',
    guidePhantom2B2: 'Введите сумму: ~{amount}€ (купите ~€5 больше на комиссии сети)',
    guidePhantom2B3: 'В списке провайдеров нажмите "Fund Your Wallet"',
    guidePhantom2B4: 'Выберите Solana (SOL)',
    guidePhantom2B5: 'Вместо MoonPay смените провайдера на Paybis — верификация документов не нужна',
    guidePhantom2B6: 'Можно оплатить: картой или Apple Pay',
    guidePhantom2Note: 'Paybis: быстрая покупка без KYC верификации документов',
    guidePhantom3T: 'Отправьте SOL нам',
    guidePhantom3B1: 'В кошельке Phantom выберите Solana',
    guidePhantom3B2: 'Нажмите "Send All"',
    guidePhantom3B3: 'Вставьте наш адрес',
    guidePhantom3B4: 'Сумма к отправке: {amount} SOL',
    guidePhantom3Note: 'После отправки напишите нам в Telegram: @Peptidai',
    guideTrustTitle: 'ПОКУПКА БЕЗ ДОКУМЕНТОВ (KYC)',
    guideTrustDesc: 'Используйте Apple Pay или карту — быстро и просто',
    guideTrust1T: 'Скачайте Trust Wallet',
    guideTrust1B1: 'Перейдите в App Store или Google Play',
    guideTrust1B2: 'Скачайте приложение "Trust Wallet"',
    guideTrust1B3: 'Создайте новый кошелёк и сохраните Seed Phrase',
    guideTrust2T: 'Купите SOL — нажмите "Fund Your Wallet"',
    guideTrust2B1: 'Нажмите кнопку "Buy" в приложении',
    guideTrust2B2: 'Выберите Solana (SOL)',
    guideTrust2B3: 'Нажмите "Fund Your Wallet"',
    guideTrust2B4: 'Выберите способ оплаты: Apple Pay',
    guideTrust2B5: 'В списке провайдеров найдите и замените MoonPay на Paybis',
    guideTrust2B6: 'Введите сумму: ~{amount}€ и оплатите',
    guideTrust2Note: 'Paybis — покупка без KYC верификации документов',
    guideTrust3T: 'Отправьте SOL нам',
    guideTrust3B1: 'Выберите SOL в своём аккаунте',
    guideTrust3B2: 'Нажмите "Send"',
    guideTrust3B3: 'Вставьте адрес нашего кошелька',
    guideTrust3B4: 'Введите сумму: {amount} SOL',
    guideTrust3B5: 'Подтвердите отправку',
    guideTrust3Note: 'После оплаты напишите: @Peptidai (Telegram)',
    guideRevolut1T: 'Откройте приложение Revolut',
    guideRevolut1B1: 'Перейдите в приложение Revolut',
    guideRevolut1B2: 'Если нет — скачайте из App Store / Google Play',
    guideRevolut2T: 'Купите SOL через Revolut',
    guideRevolut2B1: 'Перейдите в раздел "Crypto"',
    guideRevolut2B2: 'Ищите Solana (SOL)',
    guideRevolut2B3: 'Нажмите "Buy"',
    guideRevolut2B4: 'Купите SOL на ~{amount}€',
    guideRevolut3T: 'Переведите SOL на наш адрес',
    guideRevolut3B1: 'В разделе Crypto выберите SOL',
    guideRevolut3B2: 'Нажмите "Send" или "Transfer"',
    guideRevolut3B3: 'Выберите "External wallet"',
    guideRevolut3B4: 'Введите наш Solana адрес',
    guideRevolut3B5: 'Введите сумму: {amount} SOL',
    guideRevolutWarn: 'Примечание: Revolut может применять ограничения на вывод во внешний кошелёк в зависимости от уровня вашего аккаунта.',
    guideRevolutNote: 'После оплаты напишите: @Peptidai (Telegram)',
    // ProductCard
    details: 'Подробнее',
    addToCart: 'В корзину',
    // ProductDetail
    description: 'Описание',
    selectQty: 'Выберите количество',
    price: 'Цена',
    delivery: 'Доставка',
    deliveryTime: 'За 2-3 дня',
    addToCartBtn: 'Добавить в корзину',
    total: 'Итого:',
    freeShipping: 'БЕСПЛАТНО',
    paymentInfo: 'Информация об оплате',
    exactSendAmount: 'Отправить точную сумму:',
    sendToAddress: 'Отправить на адрес:',
    sendExact: 'Отправьте ТОЧНО указанную сумму',
    orderAmount: 'Сумма заказа',
    paymentMethodSol: 'Оплата через Solana (SOL)',
    exactAmountNote: 'Точная сумма будет указана на шаге оплаты',
    errorTitle: 'Ошибка:',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>('lt');

  const t = (key: string): string => {
    return translations[lang][key] ?? translations['lt'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
