/*
  # Insert accurate Omniva parcel lockers - Vilnius and Kaunas

  1. New Data
    - Real Omniva parcel locker addresses for Vilnius and Kaunas
    - Source: official Omniva locker list (pasto-kodai.lt)
    - Each address includes street, number and store/location name
*/

INSERT INTO parcel_lockers (provider, city, address, locker_code, is_active) VALUES
-- VILNIUS
('Omniva', 'Vilnius', 'Lvovo g. 25 (3 Burės parkingas)', 'OMN-VIL-001', true),
('Omniva', 'Vilnius', 'Žaliųjų Ežerų g. 207 (Balsių Maxima)', 'OMN-VIL-002', true),
('Omniva', 'Vilnius', 'Balsių g. 12 (Čia Market)', 'OMN-VIL-003', true),
('Omniva', 'Vilnius', 'Upės g. 9 (CUP)', 'OMN-VIL-004', true),
('Omniva', 'Vilnius', 'J. Jasinskio g. 1 (Express Market)', 'OMN-VIL-005', true),
('Omniva', 'Vilnius', 'Paribio g. 30B (Express Market)', 'OMN-VIL-006', true),
('Omniva', 'Vilnius', 'Polocko g. 42A (Express Market)', 'OMN-VIL-007', true),
('Omniva', 'Vilnius', 'L. Sapiegos g. 1C (Express Market)', 'OMN-VIL-008', true),
('Omniva', 'Vilnius', 'Kovo 11-osios g. 38, Grigiškės (Maxima)', 'OMN-VIL-009', true),
('Omniva', 'Vilnius', 'Bajorų kel. 4 (IKI)', 'OMN-VIL-010', true),
('Omniva', 'Vilnius', 'Buivydiškių g. 17 (IKI)', 'OMN-VIL-011', true),
('Omniva', 'Vilnius', 'Didlaukio g. 80A (IKI Baltupiai)', 'OMN-VIL-012', true),
('Omniva', 'Vilnius', 'Dzūkų g. 1 (IKI)', 'OMN-VIL-013', true),
('Omniva', 'Vilnius', 'J. Franko g. 2A (IKI)', 'OMN-VIL-014', true),
('Omniva', 'Vilnius', 'Gabijos g. 36 (IKI)', 'OMN-VIL-015', true),
('Omniva', 'Vilnius', 'Jeruzalės g. 17 (IKI)', 'OMN-VIL-016', true),
('Omniva', 'Vilnius', 'Jonažolių g. 1 (IKI)', 'OMN-VIL-017', true),
('Omniva', 'Vilnius', 'Juodasis kel. 35A (IKI)', 'OMN-VIL-018', true),
('Omniva', 'Vilnius', 'Mindaugo g. 25 (IKI)', 'OMN-VIL-019', true),
('Omniva', 'Vilnius', 'Saulėtekio al. 43 (IKI)', 'OMN-VIL-020', true),
('Omniva', 'Vilnius', 'S. Stanevičiaus g. 23 (IKI)', 'OMN-VIL-021', true),
('Omniva', 'Vilnius', 'Šeškinės g. 32 (IKI)', 'OMN-VIL-022', true),
('Omniva', 'Vilnius', 'Žemynos g. 2 (IKI)', 'OMN-VIL-023', true),
('Omniva', 'Vilnius', 'Žirmūnų g. 145 (IKI)', 'OMN-VIL-024', true),
('Omniva', 'Vilnius', 'Žirmūnų g. 2 (IKI)', 'OMN-VIL-025', true),
('Omniva', 'Vilnius', 'Loretos Asanavičiūtės g. 15 (Impuls)', 'OMN-VIL-026', true),
('Omniva', 'Vilnius', 'J. Basanavičiaus g. 29A (LPSK)', 'OMN-VIL-027', true),
('Omniva', 'Vilnius', 'Antakalnio g. 75A (Maxima)', 'OMN-VIL-028', true),
('Omniva', 'Vilnius', 'Architektų g. 152 (Maxima)', 'OMN-VIL-029', true),
('Omniva', 'Vilnius', 'Gedvydžių g. 17 (Maxima)', 'OMN-VIL-030', true),
('Omniva', 'Vilnius', 'Gilužio g. 5 (Maxima)', 'OMN-VIL-031', true),
('Omniva', 'Vilnius', 'V. Grybo g. 21 (Maxima)', 'OMN-VIL-032', true),
('Omniva', 'Vilnius', 'Kęstučio g. 37 (Maxima)', 'OMN-VIL-033', true),
('Omniva', 'Vilnius', 'Lazdynėlių g. 23 (Maxima)', 'OMN-VIL-034', true),
('Omniva', 'Vilnius', 'Medeinos g. 39 (Maxima)', 'OMN-VIL-035', true),
('Omniva', 'Vilnius', 'Mindaugo g. 11 (Maxima)', 'OMN-VIL-036', true),
('Omniva', 'Vilnius', 'Moravų g. 7 (Maxima)', 'OMN-VIL-037', true),
('Omniva', 'Vilnius', 'Naugarduko g. 84 (Maxima)', 'OMN-VIL-038', true),
('Omniva', 'Vilnius', 'Pergalės g. 42 (Maxima)', 'OMN-VIL-039', true),
('Omniva', 'Vilnius', 'Pilaitės pr. 31 (Maxima)', 'OMN-VIL-040', true),
('Omniva', 'Vilnius', 'Santaros g. 5 (Maxima)', 'OMN-VIL-041', true),
('Omniva', 'Vilnius', 'Sausio 13-osios g. 2 (Maxima)', 'OMN-VIL-042', true),
('Omniva', 'Vilnius', 'Savanorių pr. 31 (Maxima)', 'OMN-VIL-043', true),
('Omniva', 'Vilnius', 'Taikos g. 162A (Maxima)', 'OMN-VIL-044', true),
('Omniva', 'Vilnius', 'Tuskulėnų g. 66 (Maxima)', 'OMN-VIL-045', true),
('Omniva', 'Vilnius', 'Ukmergės g. 282 (Maxima)', 'OMN-VIL-046', true),
('Omniva', 'Vilnius', 'Viršuliškių g. 30 (Maxima)', 'OMN-VIL-047', true),
('Omniva', 'Vilnius', 'Šaltkalvių g. 2 (Maxima)', 'OMN-VIL-048', true),
('Omniva', 'Vilnius', 'Žalgirio g. 105 (Maxima)', 'OMN-VIL-049', true),
('Omniva', 'Vilnius', 'Pergalės g. 36 (Moki-Veži)', 'OMN-VIL-050', true),
('Omniva', 'Vilnius', 'Pilkalnio g. 3 (Moki-Veži)', 'OMN-VIL-051', true),
('Omniva', 'Vilnius', 'Ateities g. 10 (Norfa)', 'OMN-VIL-052', true),
('Omniva', 'Vilnius', 'Savanorių pr. 176 (Norfa Bazė)', 'OMN-VIL-053', true),
('Omniva', 'Vilnius', 'Genių g. 10A (Norfa)', 'OMN-VIL-054', true),
('Omniva', 'Vilnius', 'Gvazdikų Sodų 1-oji g. 1 (Norfa)', 'OMN-VIL-055', true),
('Omniva', 'Vilnius', 'A. P. Kavoliuko g. 6 (Norfa)', 'OMN-VIL-056', true),
('Omniva', 'Vilnius', 'Minsko pl. 3 (Norfa)', 'OMN-VIL-057', true),
('Omniva', 'Vilnius', 'Molėtų pl. 47 (Norfa)', 'OMN-VIL-058', true),
('Omniva', 'Vilnius', 'Parodų g. 1A (Norfa)', 'OMN-VIL-059', true),
('Omniva', 'Vilnius', 'Rygos g. 49 (Norfa)', 'OMN-VIL-060', true),
('Omniva', 'Vilnius', 'Zujūnų g. 1 (Norfa)', 'OMN-VIL-061', true),
('Omniva', 'Vilnius', 'Kalvarijų g. 151 (Norfa)', 'OMN-VIL-062', true),
('Omniva', 'Vilnius', 'Vytauto Pociūno g. 8 (Outlet Park)', 'OMN-VIL-063', true),
('Omniva', 'Vilnius', 'Ozo g. 25 (PC Akropolis)', 'OMN-VIL-064', true),
('Omniva', 'Vilnius', 'Ukmergės g. 308 (PC Domus Pro)', 'OMN-VIL-065', true),
('Omniva', 'Vilnius', 'Ateities g. 91 (PC Mandarinas)', 'OMN-VIL-066', true),
('Omniva', 'Vilnius', 'Ozo g. 18 (PC Ozas)', 'OMN-VIL-067', true),
('Omniva', 'Vilnius', 'Architektų g. 19 (Rimi Erfurtas)', 'OMN-VIL-068', true),
('Omniva', 'Vilnius', 'Ukmergės g. 233 (Rimi Fabijoniškės)', 'OMN-VIL-069', true),
('Omniva', 'Vilnius', 'Kareivių g. 11A (Rimi)', 'OMN-VIL-070', true),
('Omniva', 'Vilnius', 'Medeinos g. 8 (Rimi)', 'OMN-VIL-071', true),
('Omniva', 'Vilnius', 'Pavilnionių g. 22 (Rimi)', 'OMN-VIL-072', true),
('Omniva', 'Vilnius', 'Rygos g. 8 (Rimi)', 'OMN-VIL-073', true),
('Omniva', 'Vilnius', 'Kedrų g. 4 (Rimi Mylia)', 'OMN-VIL-074', true),
('Omniva', 'Vilnius', 'Vydūno g. 4 (Rimi Pilaitė)', 'OMN-VIL-075', true),
('Omniva', 'Vilnius', 'Zarasų g. 5A (Rimi Užupis)', 'OMN-VIL-076', true),
('Omniva', 'Vilnius', 'Šiaurės g. 37 (Rimi)', 'OMN-VIL-077', true),
('Omniva', 'Vilnius', 'Žirmūnų g. 64 (Rimi)', 'OMN-VIL-078', true),
('Omniva', 'Vilnius', 'Justiniškių g. 12 (Smėlio Arena)', 'OMN-VIL-079', true),
('Omniva', 'Vilnius', 'Salininkų g. 129A (Norfa)', 'OMN-VIL-080', true),
('Omniva', 'Vilnius', 'Vaivadiškių g. 2 (Tarandės Rimi)', 'OMN-VIL-081', true),
('Omniva', 'Vilnius', 'J. Tiškevičiaus g. 22 (Trakų Vokės Maxima)', 'OMN-VIL-082', true),
('Omniva', 'Vilnius', 'Jogailos g. 4 (VC 2000)', 'OMN-VIL-083', true),
('Omniva', 'Vilnius', 'Ukmergės g. 223 (VC Evolution)', 'OMN-VIL-084', true),
('Omniva', 'Vilnius', 'Kalvarijų g. 127 (VC Sigma)', 'OMN-VIL-085', true),
('Omniva', 'Vilnius', 'Žalgirio g. 135 (VC Žalgirio)', 'OMN-VIL-086', true),
('Omniva', 'Vilnius', 'Saltoniškių g. 12 (Viada)', 'OMN-VIL-087', true),
('Omniva', 'Vilnius', 'Nemenčinės pl. 5 (Viada)', 'OMN-VIL-088', true),

-- KAUNAS
('Omniva', 'Kaunas', 'K. Donelaičio g. 44A (Express Market)', 'OMN-KAU-001', true),
('Omniva', 'Kaunas', 'Panerių g. 166 (Express Market)', 'OMN-KAU-002', true),
('Omniva', 'Kaunas', 'Smėlio g. 7 (Express Market)', 'OMN-KAU-003', true),
('Omniva', 'Kaunas', 'Vytauto pr. 11 (Express Market)', 'OMN-KAU-004', true),
('Omniva', 'Kaunas', 'A. Šapokos g. 38 (Šilas Giraitė)', 'OMN-KAU-005', true),
('Omniva', 'Kaunas', 'Ateities pl. 4A (IKI)', 'OMN-KAU-006', true),
('Omniva', 'Kaunas', 'Kovo 11-osios g. 22 (IKI Girstutis)', 'OMN-KAU-007', true),
('Omniva', 'Kaunas', 'V. Krėvės pr. 57 (IKI)', 'OMN-KAU-008', true),
('Omniva', 'Kaunas', 'Partizanų g. 134 (IKI)', 'OMN-KAU-009', true),
('Omniva', 'Kaunas', 'Sukilėlių pr. 84 (IKI)', 'OMN-KAU-010', true),
('Omniva', 'Kaunas', 'Taikos pr. 81 (IKI)', 'OMN-KAU-011', true),
('Omniva', 'Kaunas', 'Tvirtovės al. 12A (IKI)', 'OMN-KAU-012', true),
('Omniva', 'Kaunas', 'Veiverių g. 150A (IKI)', 'OMN-KAU-013', true),
('Omniva', 'Kaunas', 'Kuršių g. 1 (Kuršių paštomatas)', 'OMN-KAU-014', true),
('Omniva', 'Kaunas', 'V. Krėvės pr. 108 (Maxima)', 'OMN-KAU-015', true),
('Omniva', 'Kaunas', 'T. Masiulio g. 16E (Maxima)', 'OMN-KAU-016', true),
('Omniva', 'Kaunas', 'Raudondvario pl. 284A (Maxima)', 'OMN-KAU-017', true),
('Omniva', 'Kaunas', 'Šiaurės pr. 8D (Maxima)', 'OMN-KAU-018', true),
('Omniva', 'Kaunas', 'Baltų pr. 195 (Norfa)', 'OMN-KAU-019', true),
('Omniva', 'Kaunas', 'Karaliaus Mindaugo pr. 49 (PC Akropolis)', 'OMN-KAU-020', true),
('Omniva', 'Kaunas', 'K. Baršausko g. 66 (PC Molas)', 'OMN-KAU-021', true),
('Omniva', 'Kaunas', 'Jonavos g. 60 (PC River Mall)', 'OMN-KAU-022', true),
('Omniva', 'Kaunas', 'Savanorių pr. 346 (PC Savas)', 'OMN-KAU-023', true),
('Omniva', 'Kaunas', 'Islandijos pl. 32 (PLC Mega)', 'OMN-KAU-024', true),
('Omniva', 'Kaunas', 'Pramonės pr. 16 (PM Urmas)', 'OMN-KAU-025', true),
('Omniva', 'Kaunas', 'Baltijos g. 58 (Rimi)', 'OMN-KAU-026', true),
('Omniva', 'Kaunas', 'Europos pr. 43 (Rimi)', 'OMN-KAU-027', true),
('Omniva', 'Kaunas', 'A. Juozapavičiaus pr. 11 (Rimi)', 'OMN-KAU-028', true),
('Omniva', 'Kaunas', 'V. Krėvės pr. 43A (Rimi)', 'OMN-KAU-029', true),
('Omniva', 'Kaunas', 'Prancūzų g. 81 (Rimi)', 'OMN-KAU-030', true),
('Omniva', 'Kaunas', 'Raudondvario pl. 94B (Rimi)', 'OMN-KAU-031', true),
('Omniva', 'Kaunas', 'Savanorių pr. 321 (Rimi)', 'OMN-KAU-032', true),
('Omniva', 'Kaunas', 'Studentų g. 19 (Rimi)', 'OMN-KAU-033', true),
('Omniva', 'Kaunas', 'Varnių g. 41 (Rimi)', 'OMN-KAU-034', true),
('Omniva', 'Kaunas', 'Rokų g. 17 (Maxima)', 'OMN-KAU-035', true),
('Omniva', 'Kaunas', 'Romainių g. 67C (Rimi)', 'OMN-KAU-036', true),
('Omniva', 'Kaunas', 'Savanorių pr. 192 (VC Nordic)', 'OMN-KAU-037', true),
('Omniva', 'Kaunas', 'A. Juozapavičiaus pr. 90 (Viada)', 'OMN-KAU-038', true),
('Omniva', 'Kaunas', 'Didžioji g. 98 (IKI Vaišvydava)', 'OMN-KAU-039', true),
('Omniva', 'Kaunas', 'Šiaurės pr. 47 (Čia Market)', 'OMN-KAU-040', true),
('Omniva', 'Kaunas', 'Baltų pr. 18 (Šilas)', 'OMN-KAU-041', true),
('Omniva', 'Kaunas', 'A. Baranausko g. 26 (Šilas)', 'OMN-KAU-042', true),
('Omniva', 'Kaunas', 'A. Juozapavičiaus pr. 81A (Šilas)', 'OMN-KAU-043', true),
('Omniva', 'Kaunas', 'Seniavos pl. 36 (Šilas)', 'OMN-KAU-044', true),
('Omniva', 'Kaunas', 'K. Sprangausko g. 1A (Šilas)', 'OMN-KAU-045', true),
('Omniva', 'Kaunas', 'Taikos pr. 31A (Šilas)', 'OMN-KAU-046', true),
('Omniva', 'Kaunas', 'Vandžiogalos pl. 22 (Šilas)', 'OMN-KAU-047', true),
('Omniva', 'Kaunas', 'K. Škirpos g. 17 (Šilas)', 'OMN-KAU-048', true),
('Omniva', 'Kaunas', 'Baltijos g. 2A (Žalia Stotelė)', 'OMN-KAU-049', true);
