/*
  # Insert accurate LP Express parcel lockers

  1. New Data
    - Real LP Express locker addresses from official Lietuvos paštas list
    - Covers all major Lithuanian cities
*/

INSERT INTO parcel_lockers (provider, city, address, locker_code, is_active) VALUES
-- VILNIUS
('LP Express', 'Vilnius', 'Ozo g. 25 (PC Akropolis)', 'LPE-VIL-101', true),
('LP Express', 'Vilnius', 'Ukmergės g. 282 (Maxima XXX)', 'LPE-VIL-102', true),
('LP Express', 'Vilnius', 'Liepkalnio g. 112 (Maxima XX)', 'LPE-VIL-103', true),
('LP Express', 'Vilnius', 'P. Lukšio g. 34 (Banginis)', 'LPE-VIL-104', true),
('LP Express', 'Vilnius', 'Gedimino pr. 7 (Centrinis paštas)', 'LPE-VIL-106', true),
('LP Express', 'Vilnius', 'J. Tiškevičiaus g. 22 (Maxima XX)', 'LPE-VIL-107', true),
('LP Express', 'Vilnius', 'Saltoniškių g. 9 (PC Panorama)', 'LPE-VIL-108', true),
('LP Express', 'Vilnius', 'Laisvės pr. 43C (Circle K)', 'LPE-VIL-110', true),
('LP Express', 'Vilnius', 'Žirmūnų g. 2 (IKI Minskas)', 'LPE-VIL-111', true),
('LP Express', 'Vilnius', 'J. Jasinskio g. 16 (Verslo trikampis)', 'LPE-VIL-112', true),
('LP Express', 'Vilnius', 'Baltupio g. 10 (Circle K)', 'LPE-VIL-113', true),
('LP Express', 'Vilnius', 'Pilaitės pr. 31 (Maxima XX)', 'LPE-VIL-114', true),
('LP Express', 'Vilnius', 'Ukmergės g. 369 (PC BIG)', 'LPE-VIL-115', true),
('LP Express', 'Vilnius', 'Mindaugo g. 25 (IKI)', 'LPE-VIL-116', true),
('LP Express', 'Vilnius', 'Tuskulėnų g. 66 (Maxima XX)', 'LPE-VIL-117', true),
('LP Express', 'Vilnius', 'Naugarduko g. 84 (Maxima XX)', 'LPE-VIL-119', true),
('LP Express', 'Vilnius', 'Geležinkelio g. 16 (Geležinkelio stotis)', 'LPE-VIL-120', true),
('LP Express', 'Vilnius', 'Fabijoniškių g. 2A (IKI Fabijoniškės)', 'LPE-VIL-121', true),
('LP Express', 'Vilnius', 'Žalgirio g. 105 (Maxima XX)', 'LPE-VIL-122', true),
('LP Express', 'Vilnius', 'Architektų g. 19 (Rimi Erfurtas)', 'LPE-VIL-123', true),
('LP Express', 'Vilnius', 'Ozo g. 18 (PC Ozas)', 'LPE-VIL-124', true),
('LP Express', 'Vilnius', 'Bajorų kelias 4 (IKI Visoriai)', 'LPE-VIL-125', true),
('LP Express', 'Vilnius', 'Nemenčinės pl. 2 (IKI Antakalnis)', 'LPE-VIL-126', true),
('LP Express', 'Vilnius', 'Architektų g. 43 (IKI Papartis)', 'LPE-VIL-127', true),
('LP Express', 'Vilnius', 'Vikingų g. 3 (PC Nordika)', 'LPE-VIL-128', true),
('LP Express', 'Vilnius', 'Jeruzalės g. 4 (Rimi)', 'LPE-VIL-129', true),
('LP Express', 'Vilnius', 'Pergalės g. 42 (Maxima XX)', 'LPE-VIL-130', true),
('LP Express', 'Vilnius', 'Taikos g. 162A (Maxima XX)', 'LPE-VIL-131', true),
('LP Express', 'Vilnius', 'Zarasų g. 5A (Rimi Užupis)', 'LPE-VIL-132', true),
('LP Express', 'Vilnius', 'Kareivių g. 11A (Rimi)', 'LPE-VIL-133', true),
('LP Express', 'Vilnius', 'Visalaukio g. 1 (IKI Žalieji ežerai)', 'LPE-VIL-134', true),
('LP Express', 'Vilnius', 'Laisvės pr. 26 (Maxima XX)', 'LPE-VIL-135', true),
('LP Express', 'Vilnius', 'Upės g. 9 (CUP)', 'LPE-VIL-136', true),
('LP Express', 'Vilnius', 'Antakalnio g. 75A (Maxima X)', 'LPE-VIL-137', true),
('LP Express', 'Vilnius', 'Mindaugo g. 11 (Maxima XXX)', 'LPE-VIL-138', true),
('LP Express', 'Vilnius', 'Savanorių pr. 176 (Norfa H)', 'LPE-VIL-139', true),
('LP Express', 'Vilnius', 'Genių g. 10A (Norfa XL)', 'LPE-VIL-140', true),
('LP Express', 'Vilnius', 'Viršuliškių g. 30 (Maxima XX)', 'LPE-VIL-141', true),
('LP Express', 'Vilnius', 'Juodasis kelias 35A (IKI Pavilnys)', 'LPE-VIL-142', true),
('LP Express', 'Vilnius', 'Ateities g. 91 (PC Mandarinas)', 'LPE-VIL-143', true),
('LP Express', 'Vilnius', 'Gabijos g. 34 (IKI Pašilaičiai)', 'LPE-VIL-144', true),
('LP Express', 'Vilnius', 'Savanorių pr. 1 (PC Helios City)', 'LPE-VIL-145', true),
('LP Express', 'Vilnius', 'Didlaukio g. 80A (IKI Baltupiai)', 'LPE-VIL-146', true),
('LP Express', 'Vilnius', 'Kedrų g. 4 (Rimi Mylia)', 'LPE-VIL-147', true),
('LP Express', 'Vilnius', 'Savanorių pr. 31 (Maxima X)', 'LPE-VIL-148', true),
('LP Express', 'Vilnius', 'Jeruzalės g. 14 (Siuntų skyrius)', 'LPE-VIL-149', true),
('LP Express', 'Vilnius', 'P. Žadeikos g. 1A (Circle K)', 'LPE-VIL-150', true),
('LP Express', 'Vilnius', 'Medeinos g. 39 (Maxima X)', 'LPE-VIL-151', true),
('LP Express', 'Vilnius', 'Ukmergės g. 308 (PC Domus Pro)', 'LPE-VIL-152', true),
('LP Express', 'Vilnius', 'Nemenčinės pl. 33 (Maxima X)', 'LPE-VIL-153', true),
('LP Express', 'Vilnius', 'Dariaus ir Girėno g. 19B (Maxima X)', 'LPE-VIL-154', true),
('LP Express', 'Vilnius', 'Rygos g. 49 (Norfa XL)', 'LPE-VIL-155', true),
('LP Express', 'Vilnius', 'Vydūno g. 4 (Rimi Pilaitė)', 'LPE-VIL-156', true),
('LP Express', 'Vilnius', 'Jonažolių g. 1 (IKI Pavasaris)', 'LPE-VIL-157', true),
('LP Express', 'Vilnius', 'Šeškinės g. 32 (IKI Šeškinė)', 'LPE-VIL-158', true),
('LP Express', 'Vilnius', 'Žirmūnų g. 64 (Rimi Šiaurės miestelis)', 'LPE-VIL-159', true),
('LP Express', 'Vilnius', 'Sausio 13-osios g. 2 (Maxima XX)', 'LPE-VIL-160', true),
('LP Express', 'Vilnius', 'Gedimino pr. 9 (VC G9)', 'LPE-VIL-161', true),
('LP Express', 'Vilnius', 'Saltoniškių g. 29 (Pigu.lt)', 'LPE-VIL-162', true),
('LP Express', 'Vilnius', 'Dominikonų g. 4 (Unipark)', 'LPE-VIL-163', true),

-- KAUNAS
('LP Express', 'Kaunas', 'Karaliaus Mindaugo pr. 49 (PC Akropolis)', 'LPE-KAU-201', true),
('LP Express', 'Kaunas', 'Savanorių pr. 255 (Maxima XXX)', 'LPE-KAU-202', true),
('LP Express', 'Kaunas', 'Veiverių g. 150B (Maxima Bazė)', 'LPE-KAU-203', true),
('LP Express', 'Kaunas', 'Raudondvario pl. 284A (Maxima XX)', 'LPE-KAU-204', true),
('LP Express', 'Kaunas', 'Islandijos pl. 32 (PLC Mega)', 'LPE-KAU-205', true),
('LP Express', 'Kaunas', 'Pramonės pr. 6 / Draugystės g. 8 (Banginis)', 'LPE-KAU-206', true),
('LP Express', 'Kaunas', 'Pramonės pr. 29 (Maxima XXX)', 'LPE-KAU-207', true),
('LP Express', 'Kaunas', 'A. Juozapavičiaus pr. 84A (Norfa XXL)', 'LPE-KAU-208', true),
('LP Express', 'Kaunas', 'Žemaičių pl. 19 (Circle K)', 'LPE-KAU-209', true),
('LP Express', 'Kaunas', 'K. Baršausko g. 57 (Circle K)', 'LPE-KAU-210', true),
('LP Express', 'Kaunas', 'K. Petrausko g. 6 (Express Market)', 'LPE-KAU-211', true),
('LP Express', 'Kaunas', 'K. Škirpos g. 17 (Šilas)', 'LPE-KAU-212', true),
('LP Express', 'Kaunas', 'Jonavos g. 3 (IKI Lituanica)', 'LPE-KAU-213', true),
('LP Express', 'Kaunas', 'Raudondvario pl. 94B (Rimi)', 'LPE-KAU-214', true),
('LP Express', 'Kaunas', 'V. Krėvės pr. 97 (IKI Saulėtekis)', 'LPE-KAU-215', true),
('LP Express', 'Kaunas', 'V. Krėvės pr. 14B (Maxima XX)', 'LPE-KAU-216', true),
('LP Express', 'Kaunas', 'Šarkuvos g. 1A (Maxima XX)', 'LPE-KAU-217', true),
('LP Express', 'Kaunas', 'K. Baršausko g. 66A (PC Molas)', 'LPE-KAU-218', true),
('LP Express', 'Kaunas', 'Baltų pr. 195 (Norfa XL)', 'LPE-KAU-219', true),
('LP Express', 'Kaunas', 'Kovo 11-osios g. 22 (IKI Girstupis)', 'LPE-KAU-220', true),
('LP Express', 'Kaunas', 'Šiaurės pr. 44 (Norfa XXL)', 'LPE-KAU-221', true),
('LP Express', 'Kaunas', 'Taikos pr. 31A (Šilas)', 'LPE-KAU-222', true),
('LP Express', 'Kaunas', 'A. Juozapavičiaus pr. 11 (Rimi)', 'LPE-KAU-223', true),
('LP Express', 'Kaunas', 'Savanorių pr. 321 (Rimi)', 'LPE-KAU-224', true),
('LP Express', 'Kaunas', 'M. K. Čiurlionio g. 16 (Geležinkelio stotis)', 'LPE-KAU-225', true),
('LP Express', 'Kaunas', 'Gimbutienės g. 3 (Šilas)', 'LPE-KAU-226', true),
('LP Express', 'Kaunas', 'Didžioji g. 98 (IKI Vaišvydava)', 'LPE-KAU-227', true),
('LP Express', 'Kaunas', 'Marių g. 2 (Express Market)', 'LPE-KAU-229', true),
('LP Express', 'Kaunas', 'Baltų pr. 81 (IKI)', 'LPE-KAU-230', true),
('LP Express', 'Kaunas', 'Varnių g. 41 (Rimi)', 'LPE-KAU-232', true),
('LP Express', 'Kaunas', 'Savanorių pr. 346 (PC Savas)', 'LPE-KAU-233', true),
('LP Express', 'Kaunas', 'Veiverių g. 35A (Lietuvos paštas)', 'LPE-KAU-234', true),
('LP Express', 'Kaunas', 'Lubinų g. 155 (Šilas)', 'LPE-KAU-235', true),
('LP Express', 'Kaunas', 'Pašilės g. 108 (Šilas)', 'LPE-KAU-236', true),

-- KLAIPĖDA
('LP Express', 'Klaipėda', 'Taikos pr. 61 (PC Akropolis)', 'LPE-KLP-301', true),
('LP Express', 'Klaipėda', 'Liepojos g. 10 (Maxima XX)', 'LPE-KLP-302', true),
('LP Express', 'Klaipėda', 'Šilutės pl. 35 (PC Banginis)', 'LPE-KLP-303', true),
('LP Express', 'Klaipėda', 'Taikos pr. 141 (PC BIG2)', 'LPE-KLP-304', true),
('LP Express', 'Klaipėda', 'Sausio 15-osios g. 1A / 2A (Circle K)', 'LPE-KLP-305', true),
('LP Express', 'Klaipėda', 'H. Manto g. 11 (Maxima X)', 'LPE-KLP-307', true),
('LP Express', 'Klaipėda', 'Taikos pr. 115 (IKI Žardė)', 'LPE-KLP-308', true),
('LP Express', 'Klaipėda', 'Liepojos g. 238 (IKI Tauralaukis)', 'LPE-KLP-309', true),
('LP Express', 'Klaipėda', 'Nidos g. 5 (IKI Naikupė)', 'LPE-KLP-310', true),
('LP Express', 'Klaipėda', 'Vingio g. 21A (Norfa XL)', 'LPE-KLP-311', true),
('LP Express', 'Klaipėda', 'Šilutės pl. 68 (Maxima XX)', 'LPE-KLP-312', true),

-- ŠIAULIAI
('LP Express', 'Šiauliai', 'Aido g. 8 (PC Akropolis)', 'LPE-SIA-401', true),
('LP Express', 'Šiauliai', 'Dubijos g. 20A (Circle K)', 'LPE-SIA-402', true),
('LP Express', 'Šiauliai', 'Tilžės g. 225 (PC Tilžė)', 'LPE-SIA-404', true),
('LP Express', 'Šiauliai', 'Gardino g. 2 (IKI Dainai)', 'LPE-SIA-405', true),
('LP Express', 'Šiauliai', 'M. Valančiaus g. 18 (Norfa XL)', 'LPE-SIA-406', true),

-- PANEVĖŽYS
('LP Express', 'Panevėžys', 'Klaipėdos g. 92 (Maxima XX)', 'LPE-PAN-501', true),
('LP Express', 'Panevėžys', 'Respublikos g. 71 (Maxima XX)', 'LPE-PAN-502', true),
('LP Express', 'Panevėžys', 'Ukmergės g. 18 (IKI Basanavičiaus)', 'LPE-PAN-503', true),
('LP Express', 'Panevėžys', 'Klaipėdos g. 143A (PC Babilonas)', 'LPE-PAN-504', true),
('LP Express', 'Panevėžys', 'Smėlynės g. 85 (Norfa XL)', 'LPE-PAN-505', true),

-- OTHER CITIES
('LP Express', 'Alytus', 'Santaikos g. 34G (Maxima XX)', 'LPE-ALY-702', true),
('LP Express', 'Alytus', 'Naujoji g. 90 (Maxima XX)', 'LPE-ALY-703', true),
('LP Express', 'Alytus', 'Topolių g. 1 (Norfa)', 'LPE-ALY-704', true),
('LP Express', 'Anykščiai', 'Žiburio g. 12 (Norfa XL)', 'LPE-ANY-3001', true),
('LP Express', 'Biržai', 'Vabalninko g. 8A (Maxima X)', 'LPE-BRZ-2701', true),
('LP Express', 'Didžioji Riešė', 'Molėtų g. 13 (IKI Riešė)', 'LPE-DRI-4901', true),
('LP Express', 'Druskininkai', 'M. K. Čiurlionio g. 50 (PC Aidas)', 'LPE-DRU-2501', true),
('LP Express', 'Elektrėnai', 'Rungos g. 4 (Maxima XX)', 'LPE-ELK-2101', true),
('LP Express', 'Elektrėnai', 'Trakų g. 4 (Lietuvos paštas)', 'LPE-ELK-240', true),
('LP Express', 'Gargždai', 'Klaipėdos g. 37 (Maxima XX)', 'LPE-GAR-4501', true),
('LP Express', 'Garliava', 'Vytauto g. 67 (IKI Garliava)', 'LPE-GRL-5001', true),
('LP Express', 'Grigiškės', 'Kovo 11-osios g. 38B (Maxima XX)', 'LPE-GRI-5101', true),
('LP Express', 'Ignalina', 'Taikos g. 11 (Maxima XX)', 'LPE-IGN-3801', true),
('LP Express', 'Jonava', 'Chemikų g. 2 (Norfa XL)', 'LPE-JON-1001', true),
('LP Express', 'Joniškis', 'Upytės g. 19 (Maxima X)', 'LPE-JNS-3101', true),
('LP Express', 'Jurbarkas', 'Algirdo g. 1A (Maxima XX)', 'LPE-JUR-2801', true),
('LP Express', 'Kaišiadorys', 'Gedimino g. 110 (Maxima X)', 'LPE-KSD-4201', true),
('LP Express', 'Kėdainiai', 'J. Basanavičiaus g. 53 (Maxima XX)', 'LPE-KED-1201', true),
('LP Express', 'Kelmė', 'S. Šilingo g. 5 (Norfa XL)', 'LPE-KEL-2901', true),
('LP Express', 'Kretinga', 'Žemaitės al. 29 (Maxima X)', 'LPE-KRE-1801', true),
('LP Express', 'Kupiškis', 'Gedimino g. 53N (Maxima XX)', 'LPE-KUP-4801', true),
('LP Express', 'Kuršėnai', 'Vilniaus g. 2 (Norfa)', 'LPE-KUR-4701', true),
('LP Express', 'Lazdijai', 'Seinų g. 1 (Viešoji biblioteka)', 'LPE-LAZ-3901', true),
('LP Express', 'Marijampolė', 'V. Kudirkos g. 3 (Maxima XXX)', 'LPE-MAR-601', true),
('LP Express', 'Marijampolė', 'Sporto g. 16 (Maxima X)', 'LPE-MAR-603', true),
('LP Express', 'Marijampolė', 'Bažnyčios g. 38 (Maxima XX)', 'LPE-MAR-604', true),
('LP Express', 'Mažeikiai', 'Laisvės g. 56 (Maxima XX)', 'LPE-MAZ-901', true),
('LP Express', 'Mažeikiai', 'Žemaitijos g. 20 (Maxima XX)', 'LPE-MAZ-902', true),
('LP Express', 'Naujoji Akmenė', 'V. Kudirkos g. 18 (Maxima XX)', 'LPE-NAK-2401', true),
('LP Express', 'Nemėžis', 'V. Sirokomlės g. 4 (Lietuvos paštas)', 'LPE-NEM-5201', true),
('LP Express', 'Palanga', 'Plytų g. 9A (Maxima X)', 'LPE-PAL-2201', true),
('LP Express', 'Pasvalys', 'Vilniaus g. 48 (Maxima X)', 'LPE-PAS-3501', true),
('LP Express', 'Plungė', 'J. Tumo-Vaižganto g. 81 (Maxima XX)', 'LPE-PLU-1701', true),
('LP Express', 'Prienai', 'Kauno g. 34 (Maxima X)', 'LPE-PRI-3201', true),
('LP Express', 'Radviliškis', 'Gedimino g. 42A (Maxima XX)', 'LPE-RAD-1901', true),
('LP Express', 'Raseiniai', 'Vilniaus g. 93 (Maxima XX)', 'LPE-RAS-2601', true),
('LP Express', 'Rokiškis', 'Respublikos g. 111B (Maxima XX)', 'LPE-ROK-2301', true),
('LP Express', 'Šakiai', 'V. Kudirkos g. 66 (Maxima X)', 'LPE-SAK-3301', true),
('LP Express', 'Šilalė', 'S. Dariaus ir S. Girėno g. 12 (Maxima X)', 'LPE-SIL-4001', true),
('LP Express', 'Šilutė', 'Lietuvininkų g. 39 (IKI)', 'LPE-SLT-2001', true),
('LP Express', 'Tauragė', 'Bernotiškės g. 3 (Norfa XL)', 'LPE-TAU-801', true),
('LP Express', 'Telšiai', 'Turgaus a. 15A (Swedbank)', 'LPE-TEL-1301', true),
('LP Express', 'Ukmergė', 'Žiedo g. 1 (Maxima XX)', 'LPE-UKM-1601', true),
('LP Express', 'Utena', 'Aušros g. 78 (Maxima XX)', 'LPE-UTE-1101', true),
('LP Express', 'Varėna', 'Savanorių g. 5 (Maxima X)', 'LPE-VAR-3401', true),
('LP Express', 'Vilkaviškis', 'J. Basanavičiaus a. 11 (Maxima XX)', 'LPE-VLK-1401', true),
('LP Express', 'Visaginas', 'Taikos g. 66 (Maxima X)', 'LPE-VIS-1501', true),
('LP Express', 'Zarasai', 'D. Bukonto g. 7 (Maxima X)', 'LPE-ZAR-3601', true);
