-- Renumber all products with new display order
UPDATE products SET display_order = 10 WHERE name = 'TESTOSTERONE E 2500MG';
UPDATE products SET display_order = 20 WHERE name = 'NAD+ 1000MG';
UPDATE products SET display_order = 30 WHERE name = 'NAD+ 500MG';
UPDATE products SET display_order = 40 WHERE name = 'GLUTATHIONE 600MG';
UPDATE products SET display_order = 50 WHERE name = 'SS-31 50MG';
UPDATE products SET display_order = 60 WHERE name = 'MOTS-C 40MG';
UPDATE products SET display_order = 70 WHERE name = 'TESAMORELIN 10MG';
UPDATE products SET display_order = 80 WHERE name = 'TESAMORELIN 20MG';
UPDATE products SET display_order = 90 WHERE name = 'RETATRUTIDE 15MG';
UPDATE products SET display_order = 100 WHERE name = 'RETATRUTIDE 30MG';
UPDATE products SET display_order = 110 WHERE name = 'TIRZEPATIDE 30MG';
UPDATE products SET display_order = 120 WHERE name = 'MELANOTAN I 10MG';
UPDATE products SET display_order = 130 WHERE name = 'MELANOTAN I 10MG NOSIES PURŠKALAS';
UPDATE products SET display_order = 140 WHERE name = 'MELANOTAN II 10MG';
UPDATE products SET display_order = 150 WHERE name = 'MELANOTAN II 10MG NOSIES PURŠKALAS';
UPDATE products SET display_order = 160 WHERE name = 'BPC-157 10MG';
UPDATE products SET display_order = 170 WHERE name = 'BPC-157 10MG + TB-500 10MG';
UPDATE products SET display_order = 180 WHERE name = 'KPV 10MG';
UPDATE products SET display_order = 190 WHERE name = 'GHK-CU 100MG';
UPDATE products SET display_order = 200 WHERE name = 'GLOW 70MG';
UPDATE products SET display_order = 210 WHERE name = 'KLOW 80MG';
UPDATE products SET display_order = 220 WHERE name = 'PT-141 10MG';
UPDATE products SET display_order = 230 WHERE name = 'HGH 24IU';
UPDATE products SET display_order = 240 WHERE name = 'HCG 10000IU';
UPDATE products SET display_order = 250 WHERE name = 'IGF-1 LR3 1MG';
UPDATE products SET display_order = 260 WHERE name = 'CJC1295 (NO DAC) 5MG + IPAMORELIN 5MG';
UPDATE products SET display_order = 270 WHERE name = 'SELANK 10MG';
UPDATE products SET display_order = 280 WHERE name = 'SELANK 10MG NOSIES PURŠKALAS';
UPDATE products SET display_order = 290 WHERE name = 'AOD-9604 10MG';
UPDATE products SET display_order = 300 WHERE name = 'DSIP 5MG';
UPDATE products SET display_order = 310 WHERE name = 'SEMAX 10MG';
UPDATE products SET display_order = 320 WHERE name = 'SEMAX 10MG NOSIES PURŠKALAS';
UPDATE products SET display_order = 330 WHERE name = 'EPITALON 50MG';
UPDATE products SET display_order = 340 WHERE name = 'LEMON BOTTLE 10ML';
UPDATE products SET display_order = 350 WHERE name = 'MASTERONE P 1000MG';
UPDATE products SET display_order = 360 WHERE name = 'MASTERONE E 2000MG';
UPDATE products SET display_order = 370 WHERE name = 'HGH 15IU';
UPDATE products SET display_order = 380 WHERE name = 'TB-500 10MG';
UPDATE products SET display_order = 390 WHERE name = '5-AMINO-1MQ 10MG';
